import { z } from 'zod';
import { LocalisedText } from '../api/common.js';
import { FormDefinition } from './definition.js';
import { V, word } from './vocabulary.js';

/**
 * Prebuilt forms somebody can start from.
 *
 * These are **code, not database rows**. A template ships with the product, has to stay valid as
 * the field schema moves, and is reviewed like any other change — a seeded table would drift the
 * moment a field type gained a required property, and nothing would notice until an author picked
 * that template. `templates.test.ts` parses every one of them against `FormDefinition`, so a
 * schema change that breaks a template fails the build rather than a customer's afternoon.
 *
 * ## What is deliberately not here
 *
 * `CLAUDE.md` rule 8 and `SPEC-forms.md` §8: **no legal, clinical, tax or safety-critical
 * wording.** That rules out most of the categories a "template gallery" would otherwise reach
 * for — incident and accident reports, medical intake, consent and waiver forms, tax
 * declarations, contracts of employment. Those templates need a human who is accountable for the
 * words, and a plausible-looking one written here would be worse than none: somebody would send
 * it out.
 *
 * The proxy form below is the one place this gets close, and it is handled by giving the
 * *structure* and leaving the authorising sentence as an explicit placeholder — see its comment.
 *
 * ## Every string, every language
 *
 * A template's text is copied into the author's draft when they pick it, so it has to be literal
 * text rather than a message key — and therefore has to exist in all twelve languages up front.
 * Generic labels come from `vocabulary.ts` so that "Email" is written once rather than twenty
 * times; only what is distinctive to a template is written here. `templates.test.ts` proves no
 * string in any template is missing a language.
 */

export const TEMPLATE_SECTORS = [
  'events',
  'services',
  'education',
  'retail',
  'membership',
  'workplace',
  'governance',
] as const;

export const TemplateSector = z.enum(TEMPLATE_SECTORS);
export type TemplateSector = z.infer<typeof TemplateSector>;

export const FormTemplate = z.object({
  id: z.string().min(1).max(64),
  sector: TemplateSector,
  name: LocalisedText,
  description: LocalisedText,
  definition: FormDefinition,
});

export type FormTemplate = z.infer<typeof FormTemplate>;

/** Twelve languages, positional. Same helper the vocabulary uses. */
const t = word;

/** The two fields nearly every form starts with, so nineteen templates do not repeat them. */
const nameField = {
  id: 'name',
  key: 'full_name',
  type: 'short_text' as const,
  label: V.fullName,
  required: true,
};

const emailField = {
  id: 'email',
  key: 'email',
  type: 'email' as const,
  label: V.email,
  required: true,
};

const phoneField = {
  id: 'phone',
  key: 'phone',
  type: 'phone' as const,
  label: V.phone,
  required: false,
};

export const FORM_TEMPLATES: FormTemplate[] = [
  {
    id: 'event-registration',
    sector: 'events',
    name: t(
      'Event registration',
      'Anmälan till evenemang',
      'Tilmelding til arrangement',
      'Påmelding til arrangement',
      'Ilmoittautuminen tapahtumaan',
      'Skráning á viðburð',
      'Inscription à un événement',
      'Veranstaltungsanmeldung',
      'Inscripción a un evento',
      '活动报名',
      'イベント申込',
      'Регистрация на мероприятие',
    ),
    description: t(
      'Name, contact details and a meal choice. Suits meetings, conferences and dinners.',
      'Namn, kontakt och matval. Passar möten, konferenser och middagar.',
      'Navn, kontakt og madvalg. Passer til møder, konferencer og middage.',
      'Navn, kontakt og måltidsvalg. Passer for møter, konferanser og middager.',
      'Nimi, yhteystiedot ja ruokavalinta. Sopii kokouksiin, konferensseihin ja illallisiin.',
      'Nafn, tengiliðaupplýsingar og máltíðarval. Hentar fundum, ráðstefnum og kvöldverðum.',
      'Nom, coordonnées et choix de repas. Convient aux réunions, conférences et dîners.',
      'Name, Kontaktdaten und Essenswunsch. Passt zu Sitzungen, Konferenzen und Abendessen.',
      'Nombre, datos de contacto y elección de comida. Sirve para reuniones, congresos y cenas.',
      '姓名、联系方式和餐食选择。适用于会议、大会和晚宴。',
      '氏名、連絡先、食事の選択。会議・カンファレンス・会食に適しています。',
      'Имя, контакты и выбор питания. Подходит для встреч, конференций и ужинов.',
    ),
    definition: FormDefinition.parse({
      schemaVersion: 1,
      fields: [
        nameField,
        emailField,
        { ...phoneField, width: 'half' },
        {
          id: 'organisation',
          key: 'organisation',
          type: 'short_text',
          label: V.organisation,
          required: false,
          width: 'half',
        },
        {
          id: 'meal',
          key: 'meal',
          type: 'single_select',
          label: V.dietary,
          required: true,
          appearance: 'radio',
          options: [
            { value: 'standard', label: V.standard },
            { value: 'vegetarian', label: V.vegetarian },
            { value: 'vegan', label: V.vegan },
            { value: 'gluten_free', label: V.glutenFree },
          ],
        },
        {
          id: 'allergies',
          key: 'allergies',
          type: 'long_text',
          label: V.allergies,
          required: false,
          rows: 2,
        },
        {
          id: 'access',
          key: 'accessibility',
          type: 'long_text',
          label: V.accessibility,
          required: false,
          rows: 2,
        },
      ],
      settings: { submitLabel: V.register, confirmationMessage: V.thanks },
    }),
  },

  {
    id: 'rsvp',
    sector: 'events',
    name: t(
      'RSVP',
      'OSA',
      'S.U.',
      'S.U.',
      'Vastaus kutsuun',
      'Svar við boði',
      'RSVP',
      'Rückmeldung',
      'Confirmación de asistencia',
      '出席回复',
      '出欠のご返事',
      'Ответ на приглашение',
    ),
    description: t(
      'The shortest possible form: are you coming, and how many of you.',
      'Kortast möjliga formulär: kommer du, och hur många är ni.',
      'Den kortest mulige formular: kommer du, og hvor mange er I.',
      'Det kortest mulige skjemaet: kommer du, og hvor mange er dere.',
      'Lyhin mahdollinen lomake: tuletko, ja montako teitä on.',
      'Stysta mögulega eyðublaðið: kemurðu, og hvað eruð þið mörg.',
      'Le formulaire le plus court possible : venez-vous, et combien serez-vous.',
      'Das kürzestmögliche Formular: Kommen Sie, und zu wie vielen.',
      'El formulario más corto posible: ¿vienes y cuántos sois?',
      '最简短的表单：您来吗，来几位。',
      'できるだけ短いフォーム：ご出席かどうかと人数だけ。',
      'Самая короткая форма: придёте ли вы и сколько вас.',
    ),
    definition: FormDefinition.parse({
      schemaVersion: 1,
      fields: [
        nameField,
        emailField,
        {
          id: 'attending',
          key: 'attending',
          type: 'single_select',
          label: t(
            'Will you be there?',
            'Kommer du?',
            'Kommer du?',
            'Kommer du?',
            'Tuletko paikalle?',
            'Kemurðu?',
            'Serez-vous présent ?',
            'Kommen Sie?',
            '¿Vas a venir?',
            '您会出席吗？',
            'ご出席されますか？',
            'Вы придёте?',
          ),
          required: true,
          appearance: 'buttons',
          options: [
            { value: 'yes', label: V.yes },
            { value: 'no', label: V.no },
            { value: 'maybe', label: V.maybe },
          ],
        },
        {
          id: 'guests',
          key: 'guests',
          type: 'number',
          label: V.numberOfPeople,
          required: false,
          min: 1,
          max: 10,
          showWhen: {
            match: 'all',
            conditions: [{ fieldKey: 'attending', operator: 'equals', value: 'yes' }],
          },
        },
        { id: 'notes', key: 'notes', type: 'long_text', label: V.notes, required: false, rows: 2 },
      ],
      settings: { submitLabel: V.send, confirmationMessage: V.thanks },
    }),
  },

  {
    id: 'contact-enquiry',
    sector: 'services',
    name: t(
      'Contact enquiry',
      'Kontaktförfrågan',
      'Kontaktformular',
      'Kontaktskjema',
      'Yhteydenottopyyntö',
      'Fyrirspurn',
      'Demande de contact',
      'Kontaktanfrage',
      'Formulario de contacto',
      '联系咨询',
      'お問い合わせ',
      'Обратная связь',
    ),
    description: t(
      'A general enquiry box. The topic list is a starting point — replace it with yours.',
      'En allmän kontaktruta. Ämneslistan är ett förslag — byt ut den mot era egna.',
      'En almindelig kontaktboks. Emnelisten er et forslag — udskift den med jeres egen.',
      'En generell kontaktboks. Emnelisten er et forslag — bytt den ut med deres egen.',
      'Yleinen yhteydenottolomake. Aiheluettelo on ehdotus — vaihda se omaksesi.',
      'Almennur fyrirspurnarreitur. Efnislistinn er tillaga — skiptu honum út fyrir þinn eigin.',
      'Une boîte de contact générale. La liste des sujets est un point de départ — remplacez-la.',
      'Ein allgemeines Kontaktfeld. Die Themenliste ist ein Vorschlag — ersetzen Sie sie.',
      'Un formulario de contacto general. La lista de temas es orientativa — cámbiala por la tuya.',
      '通用联系表单。主题列表只是起点——请换成你们自己的。',
      '一般的なお問い合わせ用です。件名の一覧は例なので、自社のものに置き換えてください。',
      'Общая форма обратной связи. Список тем — лишь отправная точка, замените его своим.',
    ),
    definition: FormDefinition.parse({
      schemaVersion: 1,
      fields: [
        nameField,
        emailField,
        { ...phoneField, width: 'half' },
        {
          id: 'topic',
          key: 'topic',
          type: 'single_select',
          label: V.subject,
          required: true,
          width: 'half',
          appearance: 'dropdown',
          options: [
            {
              value: 'sales',
              label: t(
                'Sales',
                'Försäljning',
                'Salg',
                'Salg',
                'Myynti',
                'Sala',
                'Ventes',
                'Vertrieb',
                'Ventas',
                '销售',
                '営業',
                'Продажи',
              ),
            },
            {
              value: 'support',
              label: t(
                'Support',
                'Support',
                'Support',
                'Støtte',
                'Tuki',
                'Aðstoð',
                'Assistance',
                'Support',
                'Soporte',
                '支持',
                'サポート',
                'Поддержка',
              ),
            },
            {
              value: 'billing',
              label: t(
                'Billing',
                'Fakturering',
                'Fakturering',
                'Fakturering',
                'Laskutus',
                'Reikningar',
                'Facturation',
                'Rechnungen',
                'Facturación',
                '账单',
                '請求',
                'Оплата',
              ),
            },
            { value: 'other', label: V.other },
          ],
        },
        {
          id: 'message',
          key: 'message',
          type: 'long_text',
          label: V.message,
          required: true,
          rows: 5,
        },
      ],
      settings: { submitLabel: V.send, confirmationMessage: V.thanksReply },
    }),
  },

  {
    id: 'customer-feedback',
    sector: 'retail',
    name: t(
      'Customer feedback',
      'Kundfeedback',
      'Kundefeedback',
      'Kundetilbakemelding',
      'Asiakaspalaute',
      'Umsögn viðskiptavina',
      'Avis client',
      'Kundenfeedback',
      'Opinión de clientes',
      '客户反馈',
      'お客様アンケート',
      'Отзыв клиента',
    ),
    description: t(
      'One rating and two open questions. Short forms get answered; long ones do not.',
      'Ett betyg och två öppna frågor. Korta formulär besvaras; långa gör det inte.',
      'Én bedømmelse og to åbne spørgsmål. Korte formularer bliver besvaret; lange gør ikke.',
      'Én vurdering og to åpne spørsmål. Korte skjemaer blir besvart; lange blir det ikke.',
      'Yksi arvio ja kaksi avointa kysymystä. Lyhyisiin lomakkeisiin vastataan, pitkiin ei.',
      'Ein einkunn og tvær opnar spurningar. Stuttum eyðublöðum er svarað, löngum ekki.',
      'Une note et deux questions ouvertes. Les formulaires courts obtiennent des réponses.',
      'Eine Bewertung und zwei offene Fragen. Kurze Formulare werden beantwortet, lange nicht.',
      'Una valoración y dos preguntas abiertas. Los formularios cortos se contestan; los largos no.',
      '一个评分加两个开放式问题。简短的表单才有人填。',
      '評価ひとつと自由記述ふたつ。短いフォームは回答されますが、長いものはされません。',
      'Одна оценка и два открытых вопроса. На короткие формы отвечают, на длинные — нет.',
    ),
    definition: FormDefinition.parse({
      schemaVersion: 1,
      fields: [
        {
          id: 'rating',
          key: 'rating',
          type: 'rating',
          label: t(
            'How was it?',
            'Hur var det?',
            'Hvordan var det?',
            'Hvordan var det?',
            'Millaista se oli?',
            'Hvernig var það?',
            'Comment était-ce ?',
            'Wie war es?',
            '¿Qué tal ha ido?',
            '体验如何？',
            'いかがでしたか？',
            'Как вам?',
          ),
          required: true,
          scale: 5,
          appearance: 'star',
        },
        {
          id: 'what',
          key: 'what_went_well',
          type: 'long_text',
          label: t(
            'What went well?',
            'Vad fungerade bra?',
            'Hvad gik godt?',
            'Hva gikk bra?',
            'Mikä sujui hyvin?',
            'Hvað gekk vel?',
            'Qu’est-ce qui s’est bien passé ?',
            'Was lief gut?',
            '¿Qué salió bien?',
            '哪些地方做得好？',
            'よかった点は何ですか？',
            'Что было хорошо?',
          ),
          required: false,
          rows: 3,
        },
        {
          id: 'improve',
          key: 'what_to_improve',
          type: 'long_text',
          label: t(
            'What could be better?',
            'Vad kunde bli bättre?',
            'Hvad kunne være bedre?',
            'Hva kunne vært bedre?',
            'Mikä voisi olla parempi?',
            'Hvað mætti fara betur?',
            'Qu’est-ce qui pourrait être amélioré ?',
            'Was könnte besser sein?',
            '¿Qué se podría mejorar?',
            '哪些地方可以改进？',
            'もっとよくできる点は何ですか？',
            'Что можно улучшить?',
          ),
          required: false,
          rows: 3,
        },
        {
          id: 'contact_ok',
          key: 'may_contact',
          type: 'yes_no',
          label: t(
            'May we get back to you about this?',
            'Får vi återkomma om detta?',
            'Må vi vende tilbage om dette?',
            'Kan vi ta kontakt om dette?',
            'Saammeko ottaa yhteyttä tästä?',
            'Megum við hafa samband vegna þessa?',
            'Pouvons-nous vous recontacter à ce sujet ?',
            'Dürfen wir dazu auf Sie zukommen?',
            '¿Podemos contactarte sobre esto?',
            '我们可以就此与您联系吗？',
            'この件でご連絡してもよろしいですか？',
            'Можно связаться с вами по этому поводу?',
          ),
          // Not required. The description promises a short form, and forcing an answer to the
          // one question that is about us rather than about them is how that promise breaks.
          required: false,
          appearance: 'buttons',
        },
        {
          ...emailField,
          required: false,
          showWhen: {
            match: 'all',
            conditions: [{ fieldKey: 'may_contact', operator: 'equals', value: 'true' }],
          },
        },
      ],
      settings: { submitLabel: V.send, confirmationMessage: V.thanks },
    }),
  },

  {
    id: 'satisfaction-survey',
    sector: 'retail',
    name: t(
      'Satisfaction survey',
      'Nöjdhetsundersökning',
      'Tilfredshedsundersøgelse',
      'Tilfredshetsundersøkelse',
      'Tyytyväisyyskysely',
      'Ánægjukönnun',
      'Enquête de satisfaction',
      'Zufriedenheitsumfrage',
      'Encuesta de satisfacción',
      '满意度调查',
      '満足度アンケート',
      'Опрос удовлетворённости',
    ),
    description: t(
      'A recommendation score out of ten, and room to say why.',
      'Ett rekommendationsbetyg av tio, och plats att säga varför.',
      'En anbefalingsscore ud af ti, og plads til at sige hvorfor.',
      'En anbefalingsskår av ti, og plass til å si hvorfor.',
      'Suositteluarvio kymmenestä, ja tilaa kertoa miksi.',
      'Meðmælaeinkunn af tíu, og pláss til að segja af hverju.',
      'Une note de recommandation sur dix, et la place pour expliquer pourquoi.',
      'Eine Empfehlungsbewertung von zehn, und Platz für das Warum.',
      'Una puntuación de recomendación sobre diez y espacio para explicar por qué.',
      '十分制推荐评分，以及说明理由的空间。',
      '10点満点の推奨度と、その理由を書く欄。',
      'Оценка рекомендации по десятибалльной шкале и место для объяснения.',
    ),
    definition: FormDefinition.parse({
      schemaVersion: 1,
      fields: [
        {
          id: 'score',
          key: 'recommend_score',
          type: 'rating',
          label: t(
            'How likely are you to recommend us?',
            'Hur troligt är det att du rekommenderar oss?',
            'Hvor sandsynligt er det, at du vil anbefale os?',
            'Hvor sannsynlig er det at du vil anbefale oss?',
            'Kuinka todennäköisesti suosittelisit meitä?',
            'Hversu líklegt er að þú mælir með okkur?',
            'Quelle est la probabilité que vous nous recommandiez ?',
            'Wie wahrscheinlich würden Sie uns weiterempfehlen?',
            '¿Qué probabilidad hay de que nos recomiendes?',
            '您有多大可能向他人推荐我们？',
            '当社を人にすすめる可能性はどのくらいですか？',
            'Насколько вероятно, что вы нас порекомендуете?',
          ),
          required: true,
          scale: 10,
          appearance: 'number',
          minLabel: t(
            'Not at all',
            'Inte alls',
            'Slet ikke',
            'Ikke i det hele tatt',
            'En lainkaan',
            'Alls ekki',
            'Pas du tout',
            'Überhaupt nicht',
            'Nada probable',
            '完全不会',
            'まったくない',
            'Совсем нет',
          ),
          maxLabel: t(
            'Definitely',
            'Absolut',
            'Helt sikkert',
            'Helt sikkert',
            'Ehdottomasti',
            'Örugglega',
            'Tout à fait',
            'Auf jeden Fall',
            'Sin duda',
            '一定会',
            'ぜひすすめる',
            'Обязательно',
          ),
        },
        {
          id: 'why',
          key: 'why',
          type: 'long_text',
          label: t(
            'What is the main reason for your score?',
            'Vad är den viktigaste anledningen till ditt betyg?',
            'Hvad er den vigtigste årsag til din score?',
            'Hva er hovedgrunnen til skåren din?',
            'Mikä on tärkein syy arviollesi?',
            'Hver er helsta ástæðan fyrir einkunninni?',
            'Quelle est la raison principale de votre note ?',
            'Was ist der Hauptgrund für Ihre Bewertung?',
            '¿Cuál es la razón principal de tu puntuación?',
            '给出这个分数的主要原因是什么？',
            'その点数をつけた主な理由は何ですか？',
            'Какова главная причина вашей оценки?',
          ),
          required: false,
          rows: 4,
        },
        { ...emailField, required: false },
      ],
      settings: { submitLabel: V.send, confirmationMessage: V.thanks },
    }),
  },

  {
    id: 'course-signup',
    sector: 'education',
    name: t(
      'Course sign-up',
      'Kursanmälan',
      'Kursustilmelding',
      'Kurspåmelding',
      'Kurssi-ilmoittautuminen',
      'Námskeiðsskráning',
      'Inscription à un cours',
      'Kursanmeldung',
      'Inscripción a un curso',
      '课程报名',
      '講座申込',
      'Запись на курс',
    ),
    description: t(
      'Who is coming, which course, and anything the tutor needs to know beforehand.',
      'Vem kommer, vilken kurs, och vad läraren behöver veta i förväg.',
      'Hvem kommer, hvilket kursus, og hvad underviseren skal vide på forhånd.',
      'Hvem kommer, hvilket kurs, og hva læreren trenger å vite på forhånd.',
      'Kuka tulee, mille kurssille, ja mitä opettajan pitää tietää etukäteen.',
      'Hver kemur, hvaða námskeið, og hvað kennarinn þarf að vita fyrirfram.',
      'Qui vient, quel cours, et ce que le formateur doit savoir à l’avance.',
      'Wer kommt, welcher Kurs, und was die Lehrkraft vorher wissen muss.',
      'Quién viene, a qué curso, y lo que el profesor necesita saber de antemano.',
      '谁来参加、报哪门课，以及讲师需要提前知道的事。',
      '誰が参加するか、どの講座か、講師が事前に知っておくべきこと。',
      'Кто придёт, на какой курс и что преподавателю нужно знать заранее.',
    ),
    definition: FormDefinition.parse({
      schemaVersion: 1,
      fields: [
        nameField,
        emailField,
        { ...phoneField, width: 'half' },
        {
          id: 'level',
          key: 'level',
          type: 'single_select',
          label: t(
            'Level',
            'Nivå',
            'Niveau',
            'Nivå',
            'Taso',
            'Stig',
            'Niveau',
            'Niveau',
            'Nivel',
            '级别',
            'レベル',
            'Уровень',
          ),
          required: true,
          width: 'half',
          appearance: 'radio',
          options: [
            {
              value: 'beginner',
              label: t(
                'Beginner',
                'Nybörjare',
                'Begynder',
                'Nybegynner',
                'Aloittelija',
                'Byrjandi',
                'Débutant',
                'Anfänger',
                'Principiante',
                '初级',
                '初級',
                'Начальный',
              ),
            },
            {
              value: 'intermediate',
              label: t(
                'Intermediate',
                'Medel',
                'Øvet',
                'Viderekommen',
                'Keskitaso',
                'Miðstig',
                'Intermédiaire',
                'Fortgeschritten',
                'Intermedio',
                '中级',
                '中級',
                'Средний',
              ),
            },
            {
              value: 'advanced',
              label: t(
                'Advanced',
                'Avancerad',
                'Avanceret',
                'Avansert',
                'Edistynyt',
                'Framhald',
                'Avancé',
                'Profi',
                'Avanzado',
                '高级',
                '上級',
                'Продвинутый',
              ),
            },
          ],
        },
        {
          id: 'experience',
          key: 'experience',
          type: 'long_text',
          label: t(
            'Any previous experience?',
            'Tidigare erfarenhet?',
            'Tidligere erfaring?',
            'Tidligere erfaring?',
            'Aiempaa kokemusta?',
            'Fyrri reynsla?',
            'Expérience préalable ?',
            'Vorkenntnisse?',
            '¿Experiencia previa?',
            '有相关经验吗？',
            'これまでの経験はありますか？',
            'Есть ли опыт?',
          ),
          required: false,
          rows: 3,
        },
        {
          id: 'access',
          key: 'accessibility',
          type: 'long_text',
          label: V.accessibility,
          required: false,
          rows: 2,
        },
      ],
      settings: { submitLabel: V.register, confirmationMessage: V.thanks },
    }),
  },

  {
    id: 'booking-request',
    sector: 'services',
    name: t(
      'Booking request',
      'Bokningsförfrågan',
      'Bookingforespørgsel',
      'Bestillingsforespørsel',
      'Varauspyyntö',
      'Bókunarbeiðni',
      'Demande de réservation',
      'Buchungsanfrage',
      'Solicitud de reserva',
      '预约请求',
      '予約リクエスト',
      'Запрос на бронирование',
    ),
    description: t(
      'A request, not a booking — you confirm it yourself. Replace the times with your own.',
      'En förfrågan, inte en bokning — du bekräftar själv. Byt ut tiderna mot dina egna.',
      'En forespørgsel, ikke en booking — du bekræfter selv. Udskift tiderne med dine egne.',
      'En forespørsel, ikke en bestilling — du bekrefter selv. Bytt ut tidene med dine egne.',
      'Pyyntö, ei varaus — vahvistat sen itse. Vaihda ajat omiksesi.',
      'Beiðni, ekki bókun — þú staðfestir sjálf. Skiptu tímunum út fyrir þína eigin.',
      'Une demande, pas une réservation — vous la confirmez vous-même. Remplacez les horaires.',
      'Eine Anfrage, keine Buchung — Sie bestätigen sie selbst. Ersetzen Sie die Zeiten.',
      'Una solicitud, no una reserva: la confirmas tú. Cambia los horarios por los tuyos.',
      '这是请求而非预约——由你自行确认。请把时间换成你们自己的。',
      '予約ではなくリクエストです。確定はご自身で行ってください。時間帯は自社のものに変えてください。',
      'Это запрос, а не бронь — вы подтверждаете сами. Замените время на своё.',
    ),
    definition: FormDefinition.parse({
      schemaVersion: 1,
      fields: [
        nameField,
        emailField,
        { ...phoneField, width: 'half' },
        {
          id: 'people',
          key: 'people',
          type: 'number',
          label: V.numberOfPeople,
          required: true,
          width: 'half',
          min: 1,
          max: 50,
        },
        {
          id: 'date',
          key: 'preferred_date',
          type: 'date',
          label: V.preferredDate,
          required: true,
          width: 'half',
        },
        {
          id: 'time',
          key: 'preferred_time',
          type: 'single_select',
          label: V.preferredTime,
          required: true,
          width: 'half',
          appearance: 'buttons',
          options: [
            { value: 'morning', label: V.morning },
            { value: 'afternoon', label: V.afternoon },
            { value: 'evening', label: V.evening },
          ],
        },
        { id: 'notes', key: 'notes', type: 'long_text', label: V.notes, required: false, rows: 3 },
      ],
      settings: { submitLabel: V.book, confirmationMessage: V.thanksReply },
    }),
  },

  {
    id: 'quote-request',
    sector: 'services',
    name: t(
      'Quote request',
      'Offertförfrågan',
      'Tilbudsanmodning',
      'Tilbudsforespørsel',
      'Tarjouspyyntö',
      'Beiðni um tilboð',
      'Demande de devis',
      'Angebotsanfrage',
      'Solicitud de presupuesto',
      '报价请求',
      'お見積り依頼',
      'Запрос коммерческого предложения',
    ),
    description: t(
      'What they want, when, and roughly what they expect to spend.',
      'Vad de vill ha, när, och ungefär vad de tänkt lägga.',
      'Hvad de vil have, hvornår, og cirka hvad de forventer at bruge.',
      'Hva de vil ha, når, og omtrent hva de forventer å bruke.',
      'Mitä he haluavat, milloin, ja suunnilleen paljonko aikovat käyttää.',
      'Hvað þau vilja, hvenær, og gróflega hvað þau ætla að eyða.',
      'Ce qu’ils veulent, quand, et à peu près le budget envisagé.',
      'Was sie möchten, wann, und ungefähr welches Budget.',
      'Qué quieren, cuándo y aproximadamente cuánto piensan gastar.',
      '他们想要什么、什么时候、以及大致预算。',
      'ご希望の内容、時期、おおよそのご予算。',
      'Что нужно, когда и примерный бюджет.',
    ),
    definition: FormDefinition.parse({
      schemaVersion: 1,
      fields: [
        nameField,
        emailField,
        {
          id: 'organisation',
          key: 'organisation',
          type: 'short_text',
          label: V.organisation,
          required: false,
          width: 'half',
        },
        { ...phoneField, width: 'half' },
        {
          id: 'what',
          key: 'requirement',
          type: 'long_text',
          label: t(
            'What do you need?',
            'Vad behöver ni?',
            'Hvad har I brug for?',
            'Hva trenger dere?',
            'Mitä tarvitsette?',
            'Hvað þurfið þið?',
            'De quoi avez-vous besoin ?',
            'Was brauchen Sie?',
            '¿Qué necesitáis?',
            '您需要什么？',
            'どのようなものをご希望ですか？',
            'Что вам нужно?',
          ),
          required: true,
          rows: 5,
        },
        {
          id: 'when',
          key: 'needed_by',
          type: 'date',
          label: t(
            'Needed by',
            'Behövs senast',
            'Skal bruges senest',
            'Trengs senest',
            'Tarvitaan viimeistään',
            'Þarf í síðasta lagi',
            'Nécessaire pour le',
            'Benötigt bis',
            'Se necesita para',
            '需要日期',
            '必要な時期',
            'Нужно к',
          ),
          required: false,
          width: 'half',
        },
        {
          id: 'budget',
          key: 'budget',
          type: 'short_text',
          label: t(
            'Approximate budget',
            'Ungefärlig budget',
            'Omtrentligt budget',
            'Omtrentlig budsjett',
            'Arvioitu budjetti',
            'Áætluð fjárhæð',
            'Budget approximatif',
            'Ungefähres Budget',
            'Presupuesto aproximado',
            '大致预算',
            'おおよそのご予算',
            'Примерный бюджет',
          ),
          required: false,
          width: 'half',
        },
        { id: 'files', key: 'attachment', type: 'file', label: V.attachment, required: false },
      ],
      settings: { submitLabel: V.send, confirmationMessage: V.thanksReply },
    }),
  },

  {
    id: 'support-request',
    sector: 'services',
    name: t(
      'Support request',
      'Supportärende',
      'Supportsag',
      'Støttesak',
      'Tukipyyntö',
      'Aðstoðarbeiðni',
      'Demande d’assistance',
      'Supportanfrage',
      'Solicitud de soporte',
      '支持请求',
      'サポート依頼',
      'Обращение в поддержку',
    ),
    description: t(
      'What broke, how urgent it is, and a place to attach a screenshot.',
      'Vad som gick fel, hur brådskande det är, och plats för en skärmbild.',
      'Hvad der gik galt, hvor hastende det er, og plads til et skærmbillede.',
      'Hva som gikk galt, hvor haster det, og plass til et skjermbilde.',
      'Mikä meni rikki, kuinka kiireellistä se on, ja paikka kuvakaappaukselle.',
      'Hvað bilaði, hversu brýnt það er, og pláss fyrir skjámynd.',
      'Ce qui ne va pas, l’urgence, et un endroit pour joindre une capture d’écran.',
      'Was kaputt ist, wie dringend es ist, und Platz für einen Screenshot.',
      'Qué ha fallado, con qué urgencia, y un sitio para adjuntar una captura.',
      '出了什么问题、有多紧急，以及上传截图的位置。',
      '何が起きたか、緊急度、スクリーンショットの添付欄。',
      'Что сломалось, насколько срочно, и место для скриншота.',
    ),
    definition: FormDefinition.parse({
      schemaVersion: 1,
      fields: [
        nameField,
        emailField,
        {
          id: 'urgency',
          key: 'urgency',
          type: 'single_select',
          label: t(
            'How urgent is it?',
            'Hur brådskande är det?',
            'Hvor hastende er det?',
            'Hvor mye haster det?',
            'Kuinka kiireellistä se on?',
            'Hversu brýnt er það?',
            'Quel est le degré d’urgence ?',
            'Wie dringend ist es?',
            '¿Con qué urgencia?',
            '有多紧急？',
            'どのくらい急ぎですか？',
            'Насколько это срочно?',
          ),
          required: true,
          appearance: 'radio',
          options: [
            {
              value: 'blocked',
              label: t(
                'I cannot work',
                'Jag kan inte arbeta',
                'Jeg kan ikke arbejde',
                'Jeg får ikke jobbet',
                'En pysty työskentelemään',
                'Ég get ekki unnið',
                'Je ne peux pas travailler',
                'Ich kann nicht arbeiten',
                'No puedo trabajar',
                '完全无法工作',
                '業務が止まっています',
                'Не могу работать',
              ),
            },
            {
              value: 'slow',
              label: t(
                'Working, but awkwardly',
                'Går, men krångligt',
                'Det går, men besværligt',
                'Det går, men tungvint',
                'Toimii, mutta hankalasti',
                'Gengur, en klaufalega',
                'Ça marche, mais mal',
                'Es geht, aber umständlich',
                'Funciona, pero a duras penas',
                '能用，但很不方便',
                '使えますが不便です',
                'Работает, но неудобно',
              ),
            },
            {
              value: 'minor',
              label: t(
                'Minor, no rush',
                'Litet, ingen brådska',
                'Småting, ingen hast',
                'Småtteri, ingen hast',
                'Pieni, ei kiirettä',
                'Smávægilegt, engin flýtir',
                'Mineur, pas urgent',
                'Kleinigkeit, keine Eile',
                'Menor, sin prisa',
                '小问题，不急',
                '軽微です、急ぎません',
                'Мелочь, не срочно',
              ),
            },
          ],
        },
        {
          id: 'what',
          key: 'description',
          type: 'long_text',
          label: t(
            'What happened?',
            'Vad hände?',
            'Hvad skete der?',
            'Hva skjedde?',
            'Mitä tapahtui?',
            'Hvað gerðist?',
            'Que s’est-il passé ?',
            'Was ist passiert?',
            '¿Qué ha pasado?',
            '发生了什么？',
            '何が起きましたか？',
            'Что произошло?',
          ),
          required: true,
          rows: 5,
        },
        {
          id: 'screenshot',
          key: 'screenshot',
          type: 'file',
          label: V.attachment,
          required: false,
          accept: 'image',
        },
      ],
      settings: { submitLabel: V.send, confirmationMessage: V.thanksReply },
    }),
  },

  {
    id: 'job-application',
    sector: 'workplace',
    name: t(
      'Job application',
      'Jobbansökan',
      'Jobansøgning',
      'Jobbsøknad',
      'Työhakemus',
      'Atvinnuumsókn',
      'Candidature',
      'Bewerbung',
      'Solicitud de empleo',
      '求职申请',
      '応募フォーム',
      'Заявление о приёме на работу',
    ),
    description: t(
      'Contact details, the role, and a CV. What you may lawfully ask beyond this is for you to decide.',
      'Kontaktuppgifter, tjänsten och ett CV. Vad ni får fråga därutöver avgör ni själva.',
      'Kontaktoplysninger, stillingen og et CV. Hvad I derudover må spørge om, afgør I selv.',
      'Kontaktopplysninger, stillingen og en CV. Hva dere ellers kan spørre om, avgjør dere selv.',
      'Yhteystiedot, tehtävä ja ansioluettelo. Mitä muuta saatte kysyä, päätätte itse.',
      'Tengiliðaupplýsingar, starfið og ferilskrá. Hvað þið megið spyrja umfram það ræðst hjá ykkur.',
      'Coordonnées, le poste et un CV. Ce que vous pouvez légalement demander de plus vous revient.',
      'Kontaktdaten, die Stelle und ein Lebenslauf. Was Sie darüber hinaus fragen dürfen, entscheiden Sie.',
      'Datos de contacto, el puesto y un CV. Lo que podéis preguntar además, lo decidís vosotros.',
      '联系方式、职位和简历。除此之外还能问什么，由你们自行判断。',
      '連絡先、応募職種、履歴書。これ以上何を尋ねてよいかは自社でご判断ください。',
      'Контакты, должность и резюме. Что ещё можно спрашивать — решаете вы.',
    ),
    definition: FormDefinition.parse({
      schemaVersion: 1,
      fields: [
        nameField,
        emailField,
        { ...phoneField, width: 'half' },
        {
          id: 'role',
          key: 'role',
          type: 'short_text',
          label: t(
            'Which role?',
            'Vilken tjänst?',
            'Hvilken stilling?',
            'Hvilken stilling?',
            'Mikä tehtävä?',
            'Hvaða starf?',
            'Quel poste ?',
            'Welche Stelle?',
            '¿Qué puesto?',
            '应聘哪个职位？',
            'ご応募の職種',
            'Какая должность?',
          ),
          required: true,
          width: 'half',
        },
        {
          id: 'cv',
          key: 'cv',
          type: 'file',
          label: t(
            'CV',
            'CV',
            'CV',
            'CV',
            'Ansioluettelo',
            'Ferilskrá',
            'CV',
            'Lebenslauf',
            'Currículum',
            '简历',
            '履歴書',
            'Резюме',
          ),
          required: true,
          accept: 'pdf',
        },
        {
          id: 'cover',
          key: 'cover_note',
          type: 'long_text',
          label: t(
            'Why this role?',
            'Varför den här tjänsten?',
            'Hvorfor denne stilling?',
            'Hvorfor denne stillingen?',
            'Miksi juuri tämä tehtävä?',
            'Af hverju þetta starf?',
            'Pourquoi ce poste ?',
            'Warum diese Stelle?',
            '¿Por qué este puesto?',
            '为什么应聘这个职位？',
            'この職種を志望する理由',
            'Почему именно эта должность?',
          ),
          required: false,
          rows: 5,
        },
        {
          id: 'start',
          key: 'available_from',
          type: 'date',
          label: t(
            'Available from',
            'Kan börja',
            'Kan starte',
            'Kan begynne',
            'Käytettävissä alkaen',
            'Get byrjað',
            'Disponible à partir du',
            'Verfügbar ab',
            'Disponible desde',
            '可入职日期',
            '就業可能日',
            'Готов приступить с',
          ),
          required: false,
        },
      ],
      settings: { submitLabel: V.submit, confirmationMessage: V.thanksReply },
    }),
  },

  {
    id: 'volunteer-signup',
    sector: 'membership',
    name: t(
      'Volunteer sign-up',
      'Anmälan som volontär',
      'Tilmelding som frivillig',
      'Påmelding som frivillig',
      'Vapaaehtoiseksi ilmoittautuminen',
      'Skráning sjálfboðaliða',
      'Inscription bénévole',
      'Anmeldung als Freiwillige:r',
      'Alta de voluntariado',
      '志愿者报名',
      'ボランティア登録',
      'Запись в волонтёры',
    ),
    description: t(
      'Who they are, when they can help, and what they would like to do.',
      'Vilka de är, när de kan hjälpa till, och vad de vill göra.',
      'Hvem de er, hvornår de kan hjælpe, og hvad de gerne vil lave.',
      'Hvem de er, når de kan hjelpe, og hva de har lyst til å gjøre.',
      'Keitä he ovat, milloin voivat auttaa, ja mitä haluaisivat tehdä.',
      'Hver þau eru, hvenær þau geta hjálpað, og hvað þau vilja gera.',
      'Qui ils sont, quand ils peuvent aider, et ce qu’ils aimeraient faire.',
      'Wer sie sind, wann sie helfen können und was sie gern tun würden.',
      'Quiénes son, cuándo pueden ayudar y qué les gustaría hacer.',
      '他们是谁、什么时候能帮忙、想做什么。',
      'どなたか、いつ手伝えるか、何をしたいか。',
      'Кто они, когда могут помочь и чем хотели бы заняться.',
    ),
    definition: FormDefinition.parse({
      schemaVersion: 1,
      fields: [
        nameField,
        emailField,
        { ...phoneField, width: 'half' },
        {
          id: 'availability',
          key: 'availability',
          type: 'multi_select',
          label: t(
            'When are you free?',
            'När kan du?',
            'Hvornår kan du?',
            'Når kan du?',
            'Milloin sinulle sopii?',
            'Hvenær getur þú?',
            'Quand êtes-vous disponible ?',
            'Wann haben Sie Zeit?',
            '¿Cuándo puedes?',
            '您什么时候有空？',
            'いつ都合がよいですか？',
            'Когда вам удобно?',
          ),
          required: true,
          appearance: 'checkboxes',
          options: [
            {
              value: 'weekdays',
              label: t(
                'Weekdays',
                'Vardagar',
                'Hverdage',
                'Hverdager',
                'Arkisin',
                'Virka daga',
                'En semaine',
                'Wochentags',
                'Entre semana',
                '工作日',
                '平日',
                'Будни',
              ),
            },
            {
              value: 'evenings',
              label: V.evening,
            },
            {
              value: 'weekends',
              label: t(
                'Weekends',
                'Helger',
                'Weekender',
                'Helger',
                'Viikonloppuisin',
                'Um helgar',
                'Le week-end',
                'Wochenenden',
                'Fines de semana',
                '周末',
                '週末',
                'Выходные',
              ),
            },
          ],
        },
        {
          id: 'interests',
          key: 'interests',
          type: 'long_text',
          label: t(
            'What would you like to help with?',
            'Vad vill du hjälpa till med?',
            'Hvad vil du gerne hjælpe med?',
            'Hva vil du gjerne hjelpe til med?',
            'Missä haluaisit auttaa?',
            'Með hverju vilt þú hjálpa?',
            'Sur quoi aimeriez-vous aider ?',
            'Wobei möchten Sie helfen?',
            '¿En qué te gustaría ayudar?',
            '您想帮忙做什么？',
            'どんなことを手伝いたいですか？',
            'Чем бы вы хотели помочь?',
          ),
          required: false,
          rows: 3,
        },
      ],
      settings: { submitLabel: V.register, confirmationMessage: V.thanksReply },
    }),
  },

  {
    id: 'member-details',
    sector: 'membership',
    name: t(
      'Member details',
      'Medlemsuppgifter',
      'Medlemsoplysninger',
      'Medlemsopplysninger',
      'Jäsentiedot',
      'Upplýsingar félaga',
      'Coordonnées de membre',
      'Mitgliedsdaten',
      'Datos de socio',
      '会员资料',
      '会員情報',
      'Данные участника',
    ),
    description: t(
      'Update contact details and interests. Add whatever applies to your organisation.',
      'Uppdatera kontaktuppgifter och intressen. Lägg till det som gäller just er förening.',
      'Opdater kontaktoplysninger og interesser. Tilføj det, der gælder jeres forening.',
      'Oppdater kontaktopplysninger og interesser. Legg til det som gjelder deres forening.',
      'Päivitä yhteystiedot ja kiinnostukset. Lisää se, mikä koskee juuri teidän yhdistystänne.',
      'Uppfærðu tengiliðaupplýsingar og áhugasvið. Bættu við því sem á við ykkar félag.',
      'Mettez à jour les coordonnées et les centres d’intérêt. Ajoutez ce qui vous concerne.',
      'Kontaktdaten und Interessen aktualisieren. Ergänzen Sie, was für Sie gilt.',
      'Actualiza datos de contacto e intereses. Añade lo que se aplique a tu organización.',
      '更新联系方式和兴趣。请补充适用于贵组织的内容。',
      '連絡先と関心分野の更新。自団体に当てはまる項目を追加してください。',
      'Обновление контактов и интересов. Добавьте то, что относится к вашей организации.',
    ),
    definition: FormDefinition.parse({
      schemaVersion: 1,
      fields: [
        nameField,
        emailField,
        { ...phoneField, width: 'half' },
        {
          id: 'address',
          key: 'address',
          type: 'short_text',
          label: V.address,
          required: false,
          width: 'half',
        },
        {
          id: 'postcode',
          key: 'postcode',
          type: 'short_text',
          label: V.postcode,
          required: false,
          width: 'third',
        },
        {
          id: 'city',
          key: 'city',
          type: 'short_text',
          label: V.city,
          required: false,
          width: 'third',
        },
        {
          id: 'country',
          key: 'country',
          type: 'short_text',
          label: V.country,
          required: false,
          width: 'third',
        },
        {
          id: 'newsletter',
          key: 'newsletter',
          type: 'yes_no',
          label: t(
            'Send me the newsletter',
            'Skicka nyhetsbrevet till mig',
            'Send mig nyhedsbrevet',
            'Send meg nyhetsbrevet',
            'Lähetä minulle uutiskirje',
            'Sendu mér fréttabréfið',
            'Envoyez-moi la lettre d’information',
            'Newsletter zusenden',
            'Enviadme el boletín',
            '给我发送新闻通讯',
            'ニュースレターを希望する',
            'Присылайте мне рассылку',
          ),
          required: true,
          appearance: 'buttons',
        },
      ],
      settings: { submitLabel: V.submit, confirmationMessage: V.thanks },
    }),
  },

  {
    id: 'newsletter-signup',
    sector: 'membership',
    name: t(
      'Newsletter sign-up',
      'Prenumerera på nyhetsbrev',
      'Tilmeld nyhedsbrev',
      'Meld deg på nyhetsbrev',
      'Uutiskirjeen tilaus',
      'Skráning á fréttabréf',
      'Inscription à la newsletter',
      'Newsletter-Anmeldung',
      'Alta en el boletín',
      '订阅新闻通讯',
      'ニュースレター登録',
      'Подписка на рассылку',
    ),
    description: t(
      'An address and a name. Anything more and fewer people finish it.',
      'En adress och ett namn. Mer än så och färre skriver klart.',
      'En adresse og et navn. Mere end det, og færre gør det færdigt.',
      'En adresse og et navn. Mer enn det, og færre gjør det ferdig.',
      'Osoite ja nimi. Enemmän kysyttäessä harvempi vie loppuun.',
      'Netfang og nafn. Meira en það og færri klára.',
      'Une adresse et un nom. Au-delà, moins de gens vont au bout.',
      'Eine Adresse und ein Name. Mehr, und weniger füllen es aus.',
      'Una dirección y un nombre. Más que eso, y menos gente lo termina.',
      '一个邮箱和一个名字。问得更多，填完的人就更少。',
      'メールアドレスと名前だけ。それ以上聞くと、最後まで入力する人が減ります。',
      'Адрес и имя. Спросите больше — дойдут до конца меньше людей.',
    ),
    definition: FormDefinition.parse({
      schemaVersion: 1,
      fields: [
        emailField,
        { ...nameField, required: false },
        {
          id: 'topics',
          key: 'topics',
          type: 'multi_select',
          label: t(
            'What interests you?',
            'Vad är du intresserad av?',
            'Hvad interesserer dig?',
            'Hva er du interessert i?',
            'Mikä sinua kiinnostaa?',
            'Hvað hefur þú áhuga á?',
            'Qu’est-ce qui vous intéresse ?',
            'Was interessiert Sie?',
            '¿Qué te interesa?',
            '您对什么感兴趣？',
            'どんな話題に関心がありますか？',
            'Что вам интересно?',
          ),
          required: false,
          appearance: 'checkboxes',
          options: [
            {
              value: 'news',
              label: t(
                'News',
                'Nyheter',
                'Nyheder',
                'Nyheter',
                'Uutiset',
                'Fréttir',
                'Actualités',
                'Neuigkeiten',
                'Noticias',
                '新闻',
                'ニュース',
                'Новости',
              ),
            },
            {
              value: 'events',
              label: t(
                'Events',
                'Evenemang',
                'Arrangementer',
                'Arrangementer',
                'Tapahtumat',
                'Viðburðir',
                'Événements',
                'Veranstaltungen',
                'Eventos',
                '活动',
                'イベント',
                'Мероприятия',
              ),
            },
            {
              value: 'offers',
              label: t(
                'Offers',
                'Erbjudanden',
                'Tilbud',
                'Tilbud',
                'Tarjoukset',
                'Tilboð',
                'Offres',
                'Angebote',
                'Ofertas',
                '优惠',
                'お得な情報',
                'Предложения',
              ),
            },
          ],
        },
      ],
      settings: { submitLabel: V.submit, confirmationMessage: V.thanks },
    }),
  },

  {
    id: 'suggestion-box',
    sector: 'workplace',
    name: t(
      'Suggestion box',
      'Förslagslåda',
      'Idékasse',
      'Forslagskasse',
      'Aloitelaatikko',
      'Hugmyndakassi',
      'Boîte à idées',
      'Ideenbriefkasten',
      'Buzón de sugerencias',
      '意见箱',
      'ご意見箱',
      'Ящик предложений',
    ),
    description: t(
      'Anonymous by default — the name field is optional and asked for last.',
      'Anonymt som standard — namnfältet är valfritt och kommer sist.',
      'Anonymt som standard — navnefeltet er valgfrit og kommer sidst.',
      'Anonymt som standard — navnefeltet er valgfritt og kommer sist.',
      'Oletuksena nimetön — nimikenttä on vapaaehtoinen ja kysytään viimeisenä.',
      'Nafnlaust sjálfgefið — nafnareiturinn er valfrjáls og kemur síðast.',
      'Anonyme par défaut — le champ du nom est facultatif et demandé en dernier.',
      'Standardmäßig anonym — das Namensfeld ist freiwillig und kommt zuletzt.',
      'Anónimo por defecto: el nombre es opcional y se pide al final.',
      '默认匿名——姓名为选填，且放在最后询问。',
      '既定では匿名です。氏名欄は任意で、最後に尋ねます。',
      'По умолчанию анонимно — имя необязательно и спрашивается последним.',
    ),
    definition: FormDefinition.parse({
      schemaVersion: 1,
      fields: [
        {
          id: 'idea',
          key: 'suggestion',
          type: 'long_text',
          label: t(
            'Your suggestion',
            'Ditt förslag',
            'Dit forslag',
            'Forslaget ditt',
            'Ehdotuksesi',
            'Tillagan þín',
            'Votre suggestion',
            'Ihr Vorschlag',
            'Tu sugerencia',
            '您的建议',
            'ご提案',
            'Ваше предложение',
          ),
          required: true,
          rows: 6,
        },
        {
          id: 'area',
          key: 'area',
          type: 'single_select',
          label: t(
            'What is it about?',
            'Vad gäller det?',
            'Hvad handler det om?',
            'Hva gjelder det?',
            'Mitä se koskee?',
            'Um hvað snýst það?',
            'De quoi s’agit-il ?',
            'Worum geht es?',
            '¿Sobre qué es?',
            '与什么有关？',
            'どのことについてですか？',
            'О чём это?',
          ),
          required: false,
          appearance: 'dropdown',
          options: [
            {
              value: 'workplace',
              label: t(
                'The workplace',
                'Arbetsplatsen',
                'Arbejdspladsen',
                'Arbeidsplassen',
                'Työpaikka',
                'Vinnustaðurinn',
                'Le lieu de travail',
                'Der Arbeitsplatz',
                'El lugar de trabajo',
                '工作场所',
                '職場について',
                'Рабочее место',
              ),
            },
            {
              value: 'process',
              label: t(
                'How we work',
                'Hur vi arbetar',
                'Hvordan vi arbejder',
                'Hvordan vi jobber',
                'Miten teemme työtä',
                'Hvernig við vinnum',
                'Notre façon de travailler',
                'Wie wir arbeiten',
                'Cómo trabajamos',
                '工作方式',
                '働き方について',
                'Как мы работаем',
              ),
            },
            { value: 'other', label: V.other },
          ],
        },
        { ...nameField, required: false },
      ],
      settings: { submitLabel: V.send, confirmationMessage: V.thanks },
    }),
  },

  {
    id: 'facility-booking',
    sector: 'workplace',
    name: t(
      'Room or equipment booking',
      'Boka lokal eller utrustning',
      'Book lokale eller udstyr',
      'Book rom eller utstyr',
      'Tilan tai välineen varaus',
      'Bókun á sal eða búnaði',
      'Réservation de salle ou de matériel',
      'Raum- oder Gerätebuchung',
      'Reserva de sala o equipo',
      '场地或设备预订',
      '会議室・備品の予約',
      'Бронирование помещения или оборудования',
    ),
    description: t(
      'What, when, and for how long. Replace the list with your own rooms.',
      'Vad, när och hur länge. Byt ut listan mot era egna lokaler.',
      'Hvad, hvornår og hvor længe. Udskift listen med jeres egne lokaler.',
      'Hva, når og hvor lenge. Bytt ut listen med deres egne rom.',
      'Mitä, milloin ja kuinka pitkäksi aikaa. Vaihda luettelo omiin tiloihinne.',
      'Hvað, hvenær og hversu lengi. Skiptu listanum út fyrir ykkar eigin sali.',
      'Quoi, quand et pour combien de temps. Remplacez la liste par vos salles.',
      'Was, wann und wie lange. Ersetzen Sie die Liste durch Ihre eigenen Räume.',
      'Qué, cuándo y durante cuánto tiempo. Cambia la lista por tus propias salas.',
      '预订什么、什么时候、多长时间。请把列表换成你们自己的场地。',
      '何を、いつ、どのくらい。一覧は自社の部屋に置き換えてください。',
      'Что, когда и на сколько. Замените список своими помещениями.',
    ),
    definition: FormDefinition.parse({
      schemaVersion: 1,
      fields: [
        nameField,
        emailField,
        {
          id: 'resource',
          key: 'resource',
          type: 'single_select',
          label: t(
            'What are you booking?',
            'Vad bokar du?',
            'Hvad booker du?',
            'Hva booker du?',
            'Mitä varaat?',
            'Hvað ertu að bóka?',
            'Que réservez-vous ?',
            'Was buchen Sie?',
            '¿Qué reservas?',
            '您要预订什么？',
            '何を予約しますか？',
            'Что вы бронируете?',
          ),
          required: true,
          appearance: 'dropdown',
          options: [
            {
              value: 'meeting_room',
              label: t(
                'Meeting room',
                'Mötesrum',
                'Mødelokale',
                'Møterom',
                'Kokoushuone',
                'Fundarherbergi',
                'Salle de réunion',
                'Besprechungsraum',
                'Sala de reuniones',
                '会议室',
                '会議室',
                'Переговорная',
              ),
            },
            {
              value: 'hall',
              label: t(
                'Hall',
                'Sal',
                'Sal',
                'Sal',
                'Sali',
                'Salur',
                'Salle',
                'Saal',
                'Salón',
                '大厅',
                'ホール',
                'Зал',
              ),
            },
            {
              value: 'equipment',
              label: t(
                'Equipment',
                'Utrustning',
                'Udstyr',
                'Utstyr',
                'Välineet',
                'Búnaður',
                'Matériel',
                'Ausstattung',
                'Equipo',
                '设备',
                '備品',
                'Оборудование',
              ),
            },
          ],
        },
        { id: 'date', key: 'date', type: 'date', label: V.date, required: true, width: 'third' },
        {
          id: 'from',
          key: 'from_time',
          type: 'time',
          label: t(
            'From',
            'Från',
            'Fra',
            'Fra',
            'Alkaen',
            'Frá',
            'De',
            'Von',
            'Desde',
            '从',
            '開始',
            'С',
          ),
          required: true,
          width: 'third',
        },
        {
          id: 'to',
          key: 'to_time',
          type: 'time',
          label: t(
            'To',
            'Till',
            'Til',
            'Til',
            'Asti',
            'Til',
            'À',
            'Bis',
            'Hasta',
            '到',
            '終了',
            'До',
          ),
          required: true,
          width: 'third',
        },
        {
          id: 'people',
          key: 'people',
          type: 'number',
          label: V.numberOfPeople,
          required: false,
          min: 1,
          max: 500,
        },
        { id: 'notes', key: 'notes', type: 'long_text', label: V.notes, required: false, rows: 2 },
      ],
      settings: { submitLabel: V.book, confirmationMessage: V.thanksReply },
    }),
  },

  {
    id: 'absence-notice',
    sector: 'education',
    name: t(
      'Absence notice',
      'Frånvaroanmälan',
      'Fraværsmelding',
      'Fraværsmelding',
      'Poissaoloilmoitus',
      'Fjarvistartilkynning',
      'Signalement d’absence',
      'Abwesenheitsmeldung',
      'Aviso de ausencia',
      '缺席通知',
      '欠席の連絡',
      'Уведомление об отсутствии',
    ),
    description: t(
      'Who will not be there, and for how long. Nothing about why.',
      'Vem som inte kommer, och hur länge. Inget om varför.',
      'Hvem der ikke kommer, og hvor længe. Intet om hvorfor.',
      'Hvem som ikke kommer, og hvor lenge. Ingenting om hvorfor.',
      'Kuka ei tule ja kuinka pitkään. Ei mitään syystä.',
      'Hver kemur ekki og hversu lengi. Ekkert um ástæðuna.',
      'Qui sera absent, et combien de temps. Rien sur le motif.',
      'Wer fehlt und wie lange. Nichts über den Grund.',
      'Quién faltará y cuánto tiempo. Nada sobre el motivo.',
      '谁将缺席、缺席多久。不涉及原因。',
      '誰が、どのくらい休むか。理由については尋ねません。',
      'Кто не придёт и на сколько. Ничего о причинах.',
    ),
    definition: FormDefinition.parse({
      schemaVersion: 1,
      fields: [
        {
          ...nameField,
          label: t(
            'Who is absent?',
            'Vem är frånvarande?',
            'Hvem er fraværende?',
            'Hvem er fraværende?',
            'Kuka on poissa?',
            'Hver er fjarverandi?',
            'Qui est absent ?',
            'Wer fehlt?',
            '¿Quién falta?',
            '谁缺席？',
            '欠席するのはどなたですか？',
            'Кто отсутствует?',
          ),
        },
        {
          id: 'reported_by',
          key: 'reported_by',
          type: 'short_text',
          label: t(
            'Reported by',
            'Anmäld av',
            'Meldt af',
            'Meldt av',
            'Ilmoittaja',
            'Tilkynnt af',
            'Signalé par',
            'Gemeldet von',
            'Comunicado por',
            '报告人',
            '連絡者',
            'Кто сообщает',
          ),
          required: true,
          width: 'half',
        },
        { ...phoneField, width: 'half' },
        {
          id: 'from',
          key: 'from_date',
          type: 'date',
          label: t(
            'First day away',
            'Första dagen borta',
            'Første fraværsdag',
            'Første fraværsdag',
            'Ensimmäinen poissaolopäivä',
            'Fyrsti fjarverudagur',
            'Premier jour d’absence',
            'Erster Fehltag',
            'Primer día de ausencia',
            '缺席首日',
            '欠席の初日',
            'Первый день отсутствия',
          ),
          required: true,
          width: 'half',
        },
        {
          id: 'to',
          key: 'to_date',
          type: 'date',
          label: t(
            'Expected back',
            'Tillbaka senast',
            'Tilbage senest',
            'Tilbake senest',
            'Odotettu paluu',
            'Væntanleg endurkoma',
            'Retour prévu',
            'Voraussichtlich zurück',
            'Vuelta prevista',
            '预计返回',
            '復帰予定日',
            'Ожидаемое возвращение',
          ),
          required: false,
          width: 'half',
        },
        { id: 'notes', key: 'notes', type: 'long_text', label: V.notes, required: false, rows: 2 },
      ],
      settings: { submitLabel: V.submit, confirmationMessage: V.thanks },
    }),
  },

  {
    id: 'motion-submission',
    sector: 'governance',
    name: t(
      'Motion to a meeting',
      'Motion till möte',
      'Forslag til møde',
      'Forslag til møte',
      'Aloite kokoukselle',
      'Tillaga til fundar',
      'Motion pour une assemblée',
      'Antrag an eine Versammlung',
      'Propuesta a una asamblea',
      '会议提案',
      '議案の提出',
      'Предложение к собранию',
    ),
    description: t(
      'A member puts something to the meeting: what they propose, and why.',
      'En medlem lägger fram något till mötet: vad de föreslår, och varför.',
      'Et medlem fremsætter noget til mødet: hvad de foreslår, og hvorfor.',
      'Et medlem legger fram noe for møtet: hva de foreslår, og hvorfor.',
      'Jäsen esittää kokoukselle asian: mitä ehdottaa ja miksi.',
      'Félagi leggur eitthvað fyrir fundinn: hvað hann leggur til og af hverju.',
      'Un membre soumet quelque chose à l’assemblée : ce qu’il propose, et pourquoi.',
      'Ein Mitglied bringt etwas in die Versammlung ein: was es vorschlägt und warum.',
      'Un socio presenta algo a la asamblea: qué propone y por qué.',
      '成员向会议提交议案：提议什么，以及为什么。',
      '構成員が会議に議案を出します。何を提案し、なぜそうするのか。',
      'Участник вносит вопрос на собрание: что предлагает и почему.',
    ),
    definition: FormDefinition.parse({
      schemaVersion: 1,
      fields: [
        nameField,
        emailField,
        {
          id: 'title',
          key: 'motion_title',
          type: 'short_text',
          label: t(
            'Title of the motion',
            'Motionens rubrik',
            'Forslagets overskrift',
            'Forslagets tittel',
            'Aloitteen otsikko',
            'Heiti tillögunnar',
            'Titre de la motion',
            'Titel des Antrags',
            'Título de la propuesta',
            '议案标题',
            '議案の件名',
            'Название предложения',
          ),
          required: true,
        },
        {
          id: 'background',
          key: 'background',
          type: 'long_text',
          label: t(
            'Background',
            'Bakgrund',
            'Baggrund',
            'Bakgrunn',
            'Tausta',
            'Bakgrunnur',
            'Contexte',
            'Hintergrund',
            'Antecedentes',
            '背景',
            '背景',
            'Обоснование',
          ),
          required: true,
          rows: 6,
        },
        {
          id: 'proposal',
          key: 'proposal',
          type: 'long_text',
          label: t(
            'What the meeting is asked to decide',
            'Vad mötet föreslås besluta',
            'Hvad mødet foreslås at beslutte',
            'Hva møtet foreslås å vedta',
            'Mitä kokoukselle esitetään päätettäväksi',
            'Hvað fundinum er ætlað að ákveða',
            'Ce que l’assemblée est invitée à décider',
            'Worüber die Versammlung entscheiden soll',
            'Lo que se pide decidir a la asamblea',
            '请会议决定的事项',
            '会議に決議を求める事項',
            'Что предлагается решить собранию',
          ),
          required: true,
          rows: 4,
        },
        { id: 'files', key: 'attachment', type: 'file', label: V.attachment, required: false },
      ],
      settings: { submitLabel: V.submit, confirmationMessage: V.thanksReply },
    }),
  },

  /**
   * A proxy: somebody appointing somebody else to act for them at a meeting.
   *
   * ## The wording is deliberately missing, and that is the point
   *
   * A proxy is a legal instrument. What it must say, whether it must be witnessed, how long it
   * lasts and who may hold one are all set by the organisation's own rules and by the law where
   * it sits — none of which this file can know. `CLAUDE.md` rule 8 says that wording comes from a
   * human, and a plausible-looking sentence written here would be *worse* than none, because
   * somebody would send it out believing it had been checked.
   *
   * So the template gives the **structure** — who, for whom, which meeting, what instructions,
   * signed — and puts an explicit placeholder where the authorising sentence belongs. The
   * placeholder says so in every language, and reads as an instruction to the author rather than
   * as text a respondent should ever see.
   */
  {
    id: 'meeting-proxy',
    sector: 'governance',
    name: t(
      'Proxy form',
      'Fullmakt',
      'Fuldmagt',
      'Fullmakt',
      'Valtakirja',
      'Umboð',
      'Procuration',
      'Vollmacht',
      'Delegación de voto',
      '委托书',
      '委任状',
      'Доверенность',
    ),
    description: t(
      'Structure only — the authorising wording is left blank on purpose, for a person to write.',
      'Endast struktur — fullmaktstexten är avsiktligt tom och ska skrivas av en människa.',
      'Kun struktur — fuldmagtsteksten er bevidst tom og skal skrives af et menneske.',
      'Bare struktur — fullmaktsteksten er bevisst tom og skal skrives av et menneske.',
      'Vain rakenne — valtuutusteksti on tarkoituksella tyhjä ja ihmisen kirjoitettava.',
      'Aðeins uppbygging — umboðstextinn er vísvitandi auður og manneskja á að skrifa hann.',
      'Structure seule — le texte d’autorisation est volontairement vide, à rédiger par une personne.',
      'Nur die Struktur — der Vollmachtstext bleibt bewusst leer und muss von einem Menschen stammen.',
      'Solo la estructura: el texto de autorización se deja en blanco a propósito, para que lo escriba una persona.',
      '仅提供结构——授权措辞有意留空，须由人来撰写。',
      '構成のみです。委任の文言は意図的に空欄にしてあり、人が書く必要があります。',
      'Только структура — текст доверенности намеренно оставлен пустым, его должен написать человек.',
    ),
    definition: FormDefinition.parse({
      schemaVersion: 1,
      fields: [
        {
          id: 'wording',
          key: 'authorisation_wording',
          type: 'rich_text',
          content: t(
            '[Replace this block with your own authorisation wording. A proxy is a legal instrument: what it must say, whether it needs a witness, how long it lasts and who may hold one all depend on your rules and your jurisdiction. This product does not write that sentence for you.]',
            '[Ersätt det här blocket med er egen fullmaktstext. En fullmakt är en juridisk handling: vad den måste säga, om den kräver vittne, hur länge den gäller och vem som får inneha den beror på era stadgar och er jurisdiktion. Den meningen skriver inte den här produkten åt er.]',
            '[Erstat denne blok med jeres egen fuldmagtstekst. En fuldmagt er et juridisk dokument: hvad den skal sige, om den kræver vitterlighedsvidne, hvor længe den gælder, og hvem der må have den, afhænger af jeres vedtægter og jurisdiktion. Den sætning skriver dette produkt ikke for jer.]',
            '[Erstatt denne blokken med deres egen fullmaktstekst. En fullmakt er et juridisk dokument: hva den må si, om den krever vitne, hvor lenge den gjelder og hvem som kan inneha den, avhenger av vedtektene og jurisdiksjonen deres. Den setningen skriver ikke dette produktet for dere.]',
            '[Korvaa tämä lohko omalla valtuutustekstillänne. Valtakirja on oikeudellinen asiakirja: mitä sen on sanottava, tarvitaanko todistajaa, kuinka kauan se on voimassa ja kuka sen saa haltuunsa, riippuu säännöistänne ja lainkäyttöalueestanne. Tätä lausetta tämä tuote ei kirjoita puolestanne.]',
            '[Skiptu þessum reit út fyrir ykkar eigin umboðstexta. Umboð er lögformlegt skjal: hvað það þarf að segja, hvort það krefst votts, hversu lengi það gildir og hver má fara með það ræðst af ykkar reglum og lögsögu. Þessa setningu skrifar þessi vara ekki fyrir ykkur.]',
            '[Remplacez ce bloc par votre propre texte d’autorisation. Une procuration est un acte juridique : ce qu’elle doit dire, la nécessité d’un témoin, sa durée et qui peut la détenir dépendent de vos statuts et de votre juridiction. Ce produit n’écrit pas cette phrase à votre place.]',
            '[Ersetzen Sie diesen Block durch Ihren eigenen Vollmachtstext. Eine Vollmacht ist ein Rechtsgeschäft: was sie enthalten muss, ob sie einen Zeugen braucht, wie lange sie gilt und wer sie halten darf, richtet sich nach Ihrer Satzung und Ihrer Rechtsordnung. Diesen Satz schreibt dieses Produkt nicht für Sie.]',
            '[Sustituye este bloque por tu propio texto de autorización. Una delegación de voto es un acto jurídico: qué debe decir, si requiere testigo, cuánto dura y quién puede ostentarla dependen de vuestros estatutos y de vuestra jurisdicción. Este producto no escribe esa frase por ti.]',
            '[请用你们自己的授权措辞替换本段。委托书是法律文件：它必须写明什么、是否需要见证人、有效期多久、谁可以持有，都取决于你们的章程和所在法域。本产品不会替你们写这句话。]',
            '［このブロックは自組織の委任文言に置き換えてください。委任状は法的文書です。何を記載すべきか、証人が必要か、有効期間、誰が受任できるかは、貴組織の規程と法域によって決まります。この文章を本製品が代わりに書くことはありません。］',
            '[Замените этот блок собственным текстом доверенности. Доверенность — юридический документ: что в ней должно быть написано, нужен ли свидетель, сколько она действует и кто может её держать, определяется вашим уставом и вашей юрисдикцией. Эту фразу продукт за вас не пишет.]',
          ),
        },
        {
          id: 'meeting',
          key: 'meeting',
          type: 'short_text',
          label: t(
            'Which meeting',
            'Vilket möte',
            'Hvilket møde',
            'Hvilket møte',
            'Mikä kokous',
            'Hvaða fundur',
            'Quelle assemblée',
            'Welche Versammlung',
            'Qué asamblea',
            '哪次会议',
            '対象の会議',
            'Какое собрание',
          ),
          required: true,
          width: 'half',
        },
        {
          id: 'meeting_date',
          key: 'meeting_date',
          type: 'date',
          label: V.date,
          required: true,
          width: 'half',
        },
        {
          id: 'principal',
          key: 'principal_name',
          type: 'short_text',
          label: t(
            'Name of the person giving the proxy',
            'Namn på den som ger fullmakten',
            'Navn på den, der giver fuldmagten',
            'Navn på den som gir fullmakten',
            'Valtakirjan antajan nimi',
            'Nafn þess sem veitir umboðið',
            'Nom de la personne qui donne procuration',
            'Name der vollmachtgebenden Person',
            'Nombre de quien delega',
            '出具委托的人的姓名',
            '委任する人の氏名',
            'Имя доверителя',
          ),
          required: true,
        },
        {
          id: 'principal_id',
          key: 'principal_reference',
          type: 'short_text',
          label: t(
            'Membership or shareholder reference',
            'Medlems- eller aktieägarnummer',
            'Medlems- eller aktionærnummer',
            'Medlems- eller aksjonærnummer',
            'Jäsen- tai osakastunnus',
            'Félaga- eða hluthafanúmer',
            'Référence d’adhérent ou d’actionnaire',
            'Mitglieds- oder Aktionärsnummer',
            'Referencia de socio o accionista',
            '会员或股东编号',
            '会員番号または株主番号',
            'Номер участника или акционера',
          ),
          required: false,
        },
        {
          id: 'proxy',
          key: 'proxy_name',
          type: 'short_text',
          label: t(
            'Name of the person appointed',
            'Namn på den som får fullmakten',
            'Navn på den, der får fuldmagten',
            'Navn på den som får fullmakten',
            'Valtuutetun nimi',
            'Nafn þess sem fær umboðið',
            'Nom de la personne désignée',
            'Name der bevollmächtigten Person',
            'Nombre de la persona designada',
            '受托人的姓名',
            '受任者の氏名',
            'Имя представителя',
          ),
          required: true,
        },
        {
          id: 'instructions',
          key: 'voting_instructions',
          type: 'long_text',
          label: t(
            'Voting instructions, if any',
            'Röstningsinstruktioner, om några',
            'Stemmeinstrukser, hvis nogen',
            'Stemmeinstrukser, om noen',
            'Äänestysohjeet, jos niitä on',
            'Fyrirmæli um atkvæði, ef einhver',
            'Instructions de vote, le cas échéant',
            'Weisungen zur Stimmabgabe, falls vorhanden',
            'Instrucciones de voto, si las hay',
            '投票指示（如有）',
            '議決権行使の指示（ある場合）',
            'Указания по голосованию, если есть',
          ),
          helpText: t(
            'Leave blank to let the appointed person decide.',
            'Lämna tomt för att låta den utsedda personen avgöra.',
            'Lad stå tomt for at lade den udpegede person bestemme.',
            'La stå tomt for å la den utpekte personen bestemme.',
            'Jätä tyhjäksi, jos valtuutettu saa päättää.',
            'Skildu eftir autt til að láta umboðsmanninn ráða.',
            'Laissez vide pour laisser la personne désignée décider.',
            'Leer lassen, damit die bevollmächtigte Person entscheidet.',
            'Déjalo en blanco para que decida la persona designada.',
            '留空则由受托人自行决定。',
            '空欄にすると受任者の判断に委ねられます。',
            'Оставьте пустым, чтобы решал представитель.',
          ),
          required: false,
          rows: 5,
        },
        {
          id: 'signature',
          key: 'signature',
          type: 'signature',
          label: t(
            'Signature',
            'Underskrift',
            'Underskrift',
            'Underskrift',
            'Allekirjoitus',
            'Undirskrift',
            'Signature',
            'Unterschrift',
            'Firma',
            '签名',
            '署名',
            'Подпись',
          ),
          required: true,
          statement: t(
            '[Replace with the declaration the signature confirms.]',
            '[Ersätt med den försäkran som underskriften bekräftar.]',
            '[Erstat med den erklæring, underskriften bekræfter.]',
            '[Erstatt med erklæringen underskriften bekrefter.]',
            '[Korvaa vakuutuksella, jonka allekirjoitus vahvistaa.]',
            '[Skiptu út fyrir yfirlýsinguna sem undirskriftin staðfestir.]',
            '[Remplacez par la déclaration que la signature confirme.]',
            '[Ersetzen Sie dies durch die Erklärung, die die Unterschrift bestätigt.]',
            '[Sustituye por la declaración que confirma la firma.]',
            '［请替换为签名所确认的声明。］',
            '［署名が確認する宣言文に置き換えてください。］',
            '[Замените заявлением, которое подтверждает подпись.]',
          ),
        },
      ],
      settings: { submitLabel: V.submit, confirmationMessage: V.thanks },
    }),
  },
];

/** Null, not undefined: a caller that forgets the check gets a loud failure rather than a form
 * whose fields are `undefined`. */
export function findTemplate(id: string): FormTemplate | null {
  return FORM_TEMPLATES.find((template) => template.id === id) ?? null;
}
