import type { z } from 'zod';
import type { LocalisedText as LocalisedTextSchema } from '../api/common.js';

/**
 * The words that appear in every form, in every language the product ships in.
 *
 * ## Why this exists
 *
 * A template's text is **literal**, not a message key: picking a template copies its definition
 * into the author's draft, and a key copied into a form would be meaningless the moment anybody
 * edited it. So every template carries its own strings, in every language.
 *
 * Written out per template that means twenty copies of "Name" in twelve languages — 240 chances
 * for two of them to disagree, and no way to fix "E-post" once without finding all twenty. The
 * words below are written once and composed into the templates that need them.
 *
 * ## What belongs here
 *
 * Only genuinely generic wording: the label on a name box, the options in a meal question, the
 * text on a send button. Anything specific to what a template is *for* stays in that template,
 * because sharing a sentence that only reads correctly in one context is how a catalogue starts
 * producing forms that are subtly wrong.
 *
 * `vocabulary.test.ts` proves every entry covers every shipped locale.
 */

/** One string in every shipped language. */
type Word = z.infer<typeof LocalisedTextSchema>;

/**
 * A string in every language the product ships in.
 *
 * Positional rather than an object literal on purpose: the columns line up when the entries are
 * read side by side, and the arity is what makes a forgotten language a compile error.
 */
export const word = (
  en: string,
  sv: string,
  da: string,
  nb: string,
  fi: string,
  is: string,
  fr: string,
  de: string,
  es: string,
  zh: string,
  ja: string,
  ru: string,
): Word => ({
  'en-GB': en,
  'sv-SE': sv,
  'da-DK': da,
  'nb-NO': nb,
  'fi-FI': fi,
  'is-IS': is,
  'fr-FR': fr,
  'de-DE': de,
  'es-ES': es,
  'zh-CN': zh,
  'ja-JP': ja,
  'ru-RU': ru,
});

export const V = {
  // --- Who they are -------------------------------------------------------------------------
  name: word(
    'Name',
    'Namn',
    'Navn',
    'Navn',
    'Nimi',
    'Nafn',
    'Nom',
    'Name',
    'Nombre',
    '姓名',
    '氏名',
    'Имя',
  ),
  fullName: word(
    'Full name',
    'För- och efternamn',
    'Fulde navn',
    'Fullt navn',
    'Koko nimi',
    'Fullt nafn',
    'Nom complet',
    'Vollständiger Name',
    'Nombre completo',
    '全名',
    '氏名（フルネーム）',
    'Полное имя',
  ),
  firstName: word(
    'First name',
    'Förnamn',
    'Fornavn',
    'Fornavn',
    'Etunimi',
    'Fornafn',
    'Prénom',
    'Vorname',
    'Nombre',
    '名',
    '名',
    'Имя',
  ),
  lastName: word(
    'Last name',
    'Efternamn',
    'Efternavn',
    'Etternavn',
    'Sukunimi',
    'Eftirnafn',
    'Nom de famille',
    'Nachname',
    'Apellidos',
    '姓',
    '姓',
    'Фамилия',
  ),
  email: word(
    'Email',
    'E-post',
    'E-mail',
    'E-post',
    'Sähköposti',
    'Netfang',
    'E-mail',
    'E-Mail',
    'Correo electrónico',
    '电子邮件',
    'メールアドレス',
    'Эл. почта',
  ),
  phone: word(
    'Phone',
    'Telefon',
    'Telefon',
    'Telefon',
    'Puhelin',
    'Sími',
    'Téléphone',
    'Telefon',
    'Teléfono',
    '电话',
    '電話番号',
    'Телефон',
  ),
  address: word(
    'Address',
    'Adress',
    'Adresse',
    'Adresse',
    'Osoite',
    'Heimilisfang',
    'Adresse',
    'Adresse',
    'Dirección',
    '地址',
    '住所',
    'Адрес',
  ),
  postcode: word(
    'Postcode',
    'Postnummer',
    'Postnummer',
    'Postnummer',
    'Postinumero',
    'Póstnúmer',
    'Code postal',
    'Postleitzahl',
    'Código postal',
    '邮政编码',
    '郵便番号',
    'Почтовый индекс',
  ),
  city: word(
    'Town or city',
    'Ort',
    'By',
    'Sted',
    'Paikkakunta',
    'Staður',
    'Ville',
    'Ort',
    'Localidad',
    '城市',
    '市区町村',
    'Город',
  ),
  country: word(
    'Country',
    'Land',
    'Land',
    'Land',
    'Maa',
    'Land',
    'Pays',
    'Land',
    'País',
    '国家/地区',
    '国',
    'Страна',
  ),
  organisation: word(
    'Organisation',
    'Organisation',
    'Organisation',
    'Organisasjon',
    'Organisaatio',
    'Stofnun',
    'Organisation',
    'Organisation',
    'Organización',
    '单位',
    '所属',
    'Организация',
  ),
  jobTitle: word(
    'Job title',
    'Titel',
    'Stilling',
    'Stilling',
    'Tehtävänimike',
    'Starfsheiti',
    'Fonction',
    'Position',
    'Puesto',
    '职位',
    '役職',
    'Должность',
  ),
  website: word(
    'Website',
    'Webbplats',
    'Websted',
    'Nettsted',
    'Verkkosivusto',
    'Vefsíða',
    'Site web',
    'Website',
    'Sitio web',
    '网站',
    'ウェブサイト',
    'Веб-сайт',
  ),

  // --- When and how much --------------------------------------------------------------------
  date: word(
    'Date',
    'Datum',
    'Dato',
    'Dato',
    'Päivämäärä',
    'Dagsetning',
    'Date',
    'Datum',
    'Fecha',
    '日期',
    '日付',
    'Дата',
  ),
  time: word(
    'Time',
    'Tid',
    'Tidspunkt',
    'Tidspunkt',
    'Kellonaika',
    'Tími',
    'Heure',
    'Uhrzeit',
    'Hora',
    '时间',
    '時刻',
    'Время',
  ),
  preferredDate: word(
    'Preferred date',
    'Önskat datum',
    'Ønsket dato',
    'Ønsket dato',
    'Toivottu päivämäärä',
    'Óskuð dagsetning',
    'Date souhaitée',
    'Wunschdatum',
    'Fecha preferida',
    '希望日期',
    'ご希望の日付',
    'Желаемая дата',
  ),
  preferredTime: word(
    'Preferred time',
    'Önskad tid',
    'Ønsket tidspunkt',
    'Ønsket tidspunkt',
    'Toivottu kellonaika',
    'Óskaður tími',
    'Heure souhaitée',
    'Wunschzeit',
    'Hora preferida',
    '希望时间',
    'ご希望の時間',
    'Желаемое время',
  ),
  numberOfPeople: word(
    'Number of people',
    'Antal personer',
    'Antal personer',
    'Antall personer',
    'Henkilömäärä',
    'Fjöldi',
    'Nombre de personnes',
    'Anzahl Personen',
    'Número de personas',
    '人数',
    '人数',
    'Количество человек',
  ),
  quantity: word(
    'Quantity',
    'Antal',
    'Antal',
    'Antall',
    'Määrä',
    'Fjöldi',
    'Quantité',
    'Menge',
    'Cantidad',
    '数量',
    '数量',
    'Количество',
  ),

  // --- What they want to say ----------------------------------------------------------------
  subject: word(
    'Subject',
    'Ämne',
    'Emne',
    'Emne',
    'Aihe',
    'Efni',
    'Objet',
    'Betreff',
    'Asunto',
    '主题',
    '件名',
    'Тема',
  ),
  message: word(
    'Message',
    'Meddelande',
    'Besked',
    'Melding',
    'Viesti',
    'Skilaboð',
    'Message',
    'Nachricht',
    'Mensaje',
    '内容',
    'メッセージ',
    'Сообщение',
  ),
  notes: word(
    'Anything else',
    'Övrigt',
    'Andet',
    'Annet',
    'Muuta',
    'Annað',
    'Autre chose',
    'Sonstiges',
    'Algo más',
    '其他',
    'その他',
    'Что-нибудь ещё',
  ),
  reason: word(
    'Reason',
    'Anledning',
    'Årsag',
    'Årsak',
    'Syy',
    'Ástæða',
    'Motif',
    'Grund',
    'Motivo',
    '原因',
    '理由',
    'Причина',
  ),
  comments: word(
    'Comments',
    'Kommentarer',
    'Kommentarer',
    'Kommentarer',
    'Kommentit',
    'Athugasemdir',
    'Commentaires',
    'Kommentare',
    'Comentarios',
    '意见',
    'コメント',
    'Комментарии',
  ),

  // --- Practicalities -----------------------------------------------------------------------
  dietary: word(
    'Dietary requirements',
    'Specialkost',
    'Særlige kostbehov',
    'Spesialkost',
    'Erityisruokavalio',
    'Sérfæði',
    'Régime alimentaire',
    'Ernährungswünsche',
    'Necesidades alimentarias',
    '饮食需求',
    '食事の希望',
    'Питание',
  ),
  allergies: word(
    'Allergies',
    'Allergier',
    'Allergier',
    'Allergier',
    'Allergiat',
    'Ofnæmi',
    'Allergies',
    'Allergien',
    'Alergias',
    '过敏情况',
    'アレルギー',
    'Аллергии',
  ),
  accessibility: word(
    'Access requirements',
    'Behov av tillgänglighet',
    'Behov for tilgængelighed',
    'Behov for tilgjengelighet',
    'Esteettömyystarpeet',
    'Aðgengisþarfir',
    'Besoins d’accessibilité',
    'Barrierefreiheit',
    'Necesidades de accesibilidad',
    '无障碍需求',
    'バリアフリーのご要望',
    'Доступность',
  ),
  attachment: word(
    'Attachment',
    'Bilaga',
    'Vedhæftet fil',
    'Vedlegg',
    'Liite',
    'Viðhengi',
    'Pièce jointe',
    'Anhang',
    'Archivo adjunto',
    '附件',
    '添付ファイル',
    'Вложение',
  ),
  howDidYouHear: word(
    'How did you hear about us?',
    'Hur hittade du hit?',
    'Hvordan hørte du om os?',
    'Hvordan hørte du om oss?',
    'Mistä kuulit meistä?',
    'Hvernig fréttir þú af okkur?',
    'Comment nous avez-vous connus ?',
    'Wie haben Sie von uns erfahren?',
    '¿Cómo nos conociste?',
    '您是如何了解到我们的？',
    '当方をどこでお知りになりましたか？',
    'Откуда вы о нас узнали?',
  ),

  // --- Yes, no, and the middle --------------------------------------------------------------
  yes: word('Yes', 'Ja', 'Ja', 'Ja', 'Kyllä', 'Já', 'Oui', 'Ja', 'Sí', '是', 'はい', 'Да'),
  no: word('No', 'Nej', 'Nej', 'Nei', 'Ei', 'Nei', 'Non', 'Nein', 'No', '否', 'いいえ', 'Нет'),
  maybe: word(
    'Maybe',
    'Kanske',
    'Måske',
    'Kanskje',
    'Ehkä',
    'Kannski',
    'Peut-être',
    'Vielleicht',
    'Quizá',
    '可能',
    'たぶん',
    'Возможно',
  ),
  other: word(
    'Other',
    'Annat',
    'Andet',
    'Annet',
    'Muu',
    'Annað',
    'Autre',
    'Sonstiges',
    'Otro',
    '其他',
    'その他',
    'Другое',
  ),

  morning: word(
    'Morning',
    'Förmiddag',
    'Formiddag',
    'Formiddag',
    'Aamupäivä',
    'Fyrir hádegi',
    'Matin',
    'Vormittag',
    'Mañana',
    '上午',
    '午前',
    'Утро',
  ),
  afternoon: word(
    'Afternoon',
    'Eftermiddag',
    'Eftermiddag',
    'Ettermiddag',
    'Iltapäivä',
    'Eftir hádegi',
    'Après-midi',
    'Nachmittag',
    'Tarde',
    '下午',
    '午後',
    'День',
  ),
  evening: word(
    'Evening',
    'Kväll',
    'Aften',
    'Kveld',
    'Ilta',
    'Kvöld',
    'Soir',
    'Abend',
    'Noche',
    '晚上',
    '夕方',
    'Вечер',
  ),

  standard: word(
    'Standard',
    'Standard',
    'Standard',
    'Standard',
    'Tavallinen',
    'Venjulegt',
    'Standard',
    'Standard',
    'Estándar',
    '标准',
    '標準',
    'Обычное',
  ),
  vegetarian: word(
    'Vegetarian',
    'Vegetariskt',
    'Vegetarisk',
    'Vegetarisk',
    'Kasvis',
    'Grænmetis',
    'Végétarien',
    'Vegetarisch',
    'Vegetariana',
    '素食',
    'ベジタリアン',
    'Вегетарианское',
  ),
  vegan: word(
    'Vegan',
    'Veganskt',
    'Vegansk',
    'Vegansk',
    'Vegaani',
    'Vegan',
    'Végétalien',
    'Vegan',
    'Vegana',
    '纯素',
    'ヴィーガン',
    'Веганское',
  ),
  glutenFree: word(
    'Gluten free',
    'Glutenfritt',
    'Glutenfri',
    'Glutenfri',
    'Gluteeniton',
    'Glútenlaust',
    'Sans gluten',
    'Glutenfrei',
    'Sin gluten',
    '无麸质',
    'グルテンフリー',
    'Без глютена',
  ),

  // --- Buttons and confirmations ------------------------------------------------------------
  send: word(
    'Send',
    'Skicka',
    'Send',
    'Send',
    'Lähetä',
    'Senda',
    'Envoyer',
    'Senden',
    'Enviar',
    '发送',
    '送信',
    'Отправить',
  ),
  submit: word(
    'Submit',
    'Skicka in',
    'Indsend',
    'Send inn',
    'Lähetä',
    'Senda inn',
    'Envoyer',
    'Absenden',
    'Enviar',
    '提交',
    '送信する',
    'Отправить',
  ),
  register: word(
    'Register',
    'Anmäl mig',
    'Tilmeld mig',
    'Meld meg på',
    'Ilmoittaudu',
    'Skrá mig',
    'M’inscrire',
    'Anmelden',
    'Inscribirme',
    '报名',
    '申し込む',
    'Зарегистрироваться',
  ),
  book: word(
    'Send request',
    'Skicka förfrågan',
    'Send forespørgsel',
    'Send forespørsel',
    'Lähetä pyyntö',
    'Senda beiðni',
    'Envoyer la demande',
    'Anfrage senden',
    'Enviar solicitud',
    '发送请求',
    'リクエストを送信',
    'Отправить запрос',
  ),

  thanks: word(
    'Thank you. We have your answer.',
    'Tack. Vi har fått ditt svar.',
    'Tak. Vi har modtaget dit svar.',
    'Takk. Vi har fått svaret ditt.',
    'Kiitos. Saimme vastauksesi.',
    'Takk fyrir. Við höfum fengið svarið þitt.',
    'Merci. Nous avons bien reçu votre réponse.',
    'Vielen Dank. Ihre Antwort ist bei uns eingegangen.',
    'Gracias. Hemos recibido tu respuesta.',
    '谢谢。我们已收到您的回复。',
    'ありがとうございました。回答を受け付けました。',
    'Спасибо. Мы получили ваш ответ.',
  ),
  thanksReply: word(
    'Thank you. We will be in touch.',
    'Tack. Vi hör av oss.',
    'Tak. Vi vender tilbage.',
    'Takk. Vi tar kontakt.',
    'Kiitos. Otamme yhteyttä.',
    'Takk fyrir. Við höfum samband.',
    'Merci. Nous vous recontacterons.',
    'Vielen Dank. Wir melden uns bei Ihnen.',
    'Gracias. Nos pondremos en contacto.',
    '谢谢。我们会与您联系。',
    'ありがとうございました。追ってご連絡します。',
    'Спасибо. Мы свяжемся с вами.',
  ),

  // --- Meetings and records ------------------------------------------------------------------
  meeting: word(
    'Meeting',
    'Möte',
    'Møde',
    'Møte',
    'Kokous',
    'Fundur',
    'Réunion',
    'Sitzung',
    'Reunión',
    '会议',
    '会議',
    'Собрание',
  ),
  memberNumber: word(
    'Membership number',
    'Medlemsnummer',
    'Medlemsnummer',
    'Medlemsnummer',
    'Jäsennumero',
    'Félaganúmer',
    'Numéro d’adhérent',
    'Mitgliedsnummer',
    'Número de socio',
    '会员编号',
    '会員番号',
    'Номер участника',
  ),
  location: word(
    'Location',
    'Plats',
    'Sted',
    'Sted',
    'Sijainti',
    'Staðsetning',
    'Lieu',
    'Ort',
    'Lugar',
    '地点',
    '場所',
    'Место',
  ),
  reference: word(
    'Reference',
    'Referens',
    'Reference',
    'Referanse',
    'Viite',
    'Tilvísun',
    'Référence',
    'Referenz',
    'Referencia',
    '编号',
    '参照番号',
    'Ссылка',
  ),
  recordedBy: word(
    'Recorded by',
    'Noterat av',
    'Registreret af',
    'Registrert av',
    'Kirjannut',
    'Skráð af',
    'Enregistré par',
    'Erfasst von',
    'Registrado por',
    '记录人',
    '記録者',
    'Записал',
  ),
  method: word(
    'Method',
    'Metod',
    'Metode',
    'Metode',
    'Menetelmä',
    'Aðferð',
    'Méthode',
    'Methode',
    'Método',
    '方法',
    '方法',
    'Метод',
  ),
  equipment: word(
    'Equipment',
    'Utrustning',
    'Udstyr',
    'Utstyr',
    'Välineet',
    'Búnaður',
    'Matériel',
    'Ausstattung',
    'Equipo',
    '设备',
    '機材',
    'Оборудование',
  ),
  conditions: word(
    'Conditions',
    'Förhållanden',
    'Forhold',
    'Forhold',
    'Olosuhteet',
    'Aðstæður',
    'Conditions',
    'Bedingungen',
    'Condiciones',
    '条件',
    '条件',
    'Условия',
  ),
  temperature: word(
    'Temperature (°C)',
    'Temperatur (°C)',
    'Temperatur (°C)',
    'Temperatur (°C)',
    'Lämpötila (°C)',
    'Hitastig (°C)',
    'Température (°C)',
    'Temperatur (°C)',
    'Temperatura (°C)',
    '温度（°C）',
    '温度（℃）',
    'Температура (°C)',
  ),
  observation: word(
    'Observation',
    'Observation',
    'Observation',
    'Observasjon',
    'Havainto',
    'Athugun',
    'Observation',
    'Beobachtung',
    'Observación',
    '观察结果',
    '観察結果',
    'Наблюдение',
  ),
  sampleId: word(
    'Sample identifier',
    'Prov-ID',
    'Prøve-id',
    'Prøve-ID',
    'Näytetunnus',
    'Auðkenni sýnis',
    'Identifiant d’échantillon',
    'Proben-Kennung',
    'Identificador de muestra',
    '样本编号',
    '検体ID',
    'Идентификатор образца',
  ),
  collectedOn: word(
    'Collected on',
    'Insamlat',
    'Indsamlet',
    'Innsamlet',
    'Kerätty',
    'Safnað',
    'Prélevé le',
    'Entnommen am',
    'Recogida el',
    '采集日期',
    '採取日',
    'Дата отбора',
  ),
} as const satisfies Record<string, Word>;

export type VocabularyKey = keyof typeof V;
