import type { BuilderGraph } from './schema.js';

/**
 * The guided conversation — slice S1's fifteen nodes, plus the menu every node can escape to and
 * the end (`docs/plan/BUILDER-GRAPH.md`, "The nodes of slice S1").
 *
 * **This is data, not code.** `graph.test.ts` proves it round-trips through JSON unchanged — no
 * functions, no `undefined`, nothing a server could not send. It is TypeScript rather than JSON
 * only so the compiler checks it as it is typed and so it can carry these comments (ADR 0021).
 *
 * Every string is a message key in `apps/forms/src/lib/messages`, in all twelve catalogues; the
 * words live there. `pnpm builder:validate` checks every key exists, every question is at most
 * nine words in English, and no banned word appears (rules G4, G10).
 *
 * **Scores** are millinats added to a template's belief when the option is chosen (ADR 0019). They
 * are guesses about evidence, set by a person and reviewed like any other number here: "signing
 * people up" is strong evidence for an event registration and weak evidence for an RSVP.
 *
 * **Version 2 (S5)** offers the `tab` and `segmented` shapes, which `ChoiceStyle` gained in that
 * slice, and writes the logo slot into the form (`settings.layout.logoSlot`) rather than keeping
 * it in `pending`. A session recorded against version 1 still replays: the log holds resolved
 * changes, not the options that caused them.
 *
 * **Version 3 (S6)** says which slot each node of a question settles (`slot`), so a sentence that
 * answers several at once — "three buttons, pill shape, side by side" — can answer them ahead of
 * their turn, and the conversation passes them by when it gets there instead of asking again.
 * "One answer or several?" and "Where should they sit?" gained the `decided()` guard that does it.
 *
 * **Version 4 (owner question 8)** asks "Which colours should your form use?" only of someone who
 * may change the organisation's colours (`pending.canChangeBrand`, an administrator): a preset takes
 * effect only through the brand kit, which is every form's and every mail's. Anyone else passes it
 * by, told why. What the administrator picks is applied only once they confirm it, on the screen.
 *
 * **Version 5 (S11)** is the guess (`docs/plan/BELIEF.md`). Twenty-two yes / no / not sure questions,
 * group `guess`, tell the recipes apart; after "What is this form for?" the machine asks the one
 * expected to tell it most (`next: { best: 'guess', else }`), up to five, until one recipe is at
 * 800 per mille. A score is now how much likelier a person building that recipe is to choose the
 * option, as a log over the node's scored options, so `flow.start`'s scores are re-set on that
 * scale: a recipe no option names is indifferent to the question. "Right" seeds the recipe, and the
 * conversation goes on with only the gaps: the brand, then "Add another question?".
 *
 * **Version 6 (S12)** walks a form read from a document (`docs/plan/CONVERGENCE.md`, acceptance
 * S6): "Use these questions" leads to "Go through the questions from your document?", and each
 * question it walks goes through the chain every question goes through, which passes by what the
 * document decided. The choice chain also serves a question that is a choice before the
 * conversation met it, and a shape shows the question as buttons.
 *
 * **Version 7 (S13)** makes acceptance S1 possible by clicking alone (`docs/plan/POLISH.md`): "What
 * is your form called?" between the guess and the brand, so the form has its heading and the
 * masthead its name; and after "No buttons", "How should people answer?" — a line, a few sentences,
 * or a box to tick, the last of which is a consent's presentation, its words the person's own.
 */
export const BUILDER_GRAPH = {
  graphVersion: 7,
  start: 'flow.start',
  // What the machine or the screen provides, not a patch: `guess.pMille` and `pending.seeded` are
  // the belief engine's (S11), `pending.toWalk` the walk's (S12), the rest the screen's at the start.
  inputs: [
    'pending.brandKitExists',
    'pending.canChangeBrand',
    'guess.pMille',
    'pending.seeded',
    'pending.toWalk',
  ],
  nodes: [
    {
      id: 'flow.start',
      group: 'flow',
      kind: 'question',
      ask: 'guided.flow.start.ask',
      help: 'guided.flow.start.help',
      next: { best: 'guess', else: 'guess.confirm' },
      escape: 'menu.top',
      options: [
        {
          id: 'signup',
          label: 'guided.flow.start.signup',
          detail: 'guided.flow.start.signupDetail',
          icon: 'events',
          // Publishable from the first answer: every door adds a real question at once.
          patch: [
            { op: 'set', path: 'pending.purpose', value: 'signup' },
            {
              op: 'add',
              path: 'draft.definition.fields',
              value: {
                $newField: { type: 'short_text', word: 'name', key: 'name', required: true },
              },
            },
          ],
          score: {
            'event-registration': 3500,
            'course-signup': 3500,
            'conference-registration': 3500,
            'general-meeting-registration': 3500,
            rsvp: 2800,
            'volunteer-signup': 2800,
            'newsletter-signup': 2800,
            'facility-booking': 1400,
            'booking-request': 1100,
          },
        },
        {
          id: 'collect',
          label: 'guided.flow.start.collect',
          detail: 'guided.flow.start.collectDetail',
          icon: 'forms',
          patch: [
            { op: 'set', path: 'pending.purpose', value: 'collect' },
            {
              op: 'add',
              path: 'draft.definition.fields',
              value: {
                $newField: { type: 'short_text', word: 'name', key: 'name', required: true },
              },
            },
          ],
          score: {
            'member-details': 3500,
            'job-application': 3500,
            'lab-observation': 3500,
            'sample-submission': 3500,
            'incident-report': 3500,
            'contact-enquiry': 2800,
            'absence-notice': 2800,
            'motion-submission': 2800,
            'meeting-proxy': 2800,
            'power-of-attorney': 2800,
            'consent-form': 2800,
            'quote-request': 2100,
            'support-request': 2100,
            'booking-request': 2100,
            'facility-booking': 2100,
          },
        },
        {
          id: 'feedback',
          label: 'guided.flow.start.feedback',
          detail: 'guided.flow.start.feedbackDetail',
          icon: 'edit',
          patch: [
            { op: 'set', path: 'pending.purpose', value: 'feedback' },
            {
              op: 'add',
              path: 'draft.definition.fields',
              value: { $newField: { type: 'long_text', word: 'comments', key: 'comments' } },
            },
          ],
          score: {
            'customer-feedback': 3500,
            'satisfaction-survey': 3500,
            'suggestion-box': 3500,
          },
        },
        {
          id: 'other',
          label: 'guided.flow.start.other',
          detail: 'guided.flow.start.otherDetail',
          icon: 'plus',
          patch: [
            { op: 'set', path: 'pending.purpose', value: 'other' },
            {
              op: 'add',
              path: 'draft.definition.fields',
              value: { $newField: { type: 'short_text', word: 'name', key: 'name' } },
            },
          ],
        },
      ],
    },
    {
      id: 'guess.confirm',
      group: 'guess',
      kind: 'confirm-guess',
      ask: 'guided.guess.ask',
      help: 'guided.guess.help',
      when: 'guess.pMille >= 800 && !has(pending.seeded)',
      skip: [
        { when: 'has(pending.seeded)', skip: 'guided.skip.seeded' },
        { when: 'true', skip: 'guided.skip.nothingToGuess' },
      ],
      // Sort of and No ask on, if a question is still worth asking; Right has nothing left to guess.
      // After No, another recipe may already be sure enough — then it is the one asked about.
      next: {
        best: 'guess',
        else: [
          { when: 'has(pending.seeded)', to: 'guess.seeded' },
          { when: 'guess.pMille >= 800', to: 'guess.confirm' },
          { when: 'true', to: 'flow.title' },
        ],
      },
      escape: 'menu.top',
    },
    {
      // What "Right" added, as the form will look — every question of it editable in place (brief
      // §6: "show what was seeded and let every seeded field be edited inline").
      id: 'guess.seeded',
      group: 'guess',
      kind: 'preview-moment',
      ask: 'guided.preview.ask',
      help: 'guided.guess.seeded.help',
      when: 'has(pending.seeded)',
      skip: 'guided.skip.nothingSeeded',
      preview: 'form.whole',
      next: 'flow.title',
      escape: 'menu.top',
    },
    // The guess questions (S11, `docs/plan/BELIEF.md`). Each changes nothing in the form: its
    // answer only moves the belief. "Yes" names the recipes a person building them would say yes
    // for, "No" those they would say no for, and how surely, in millinats; a recipe named on
    // neither side is indifferent to the question. "Not sure" has no score, and says nothing.
    {
      id: 'guess.date',
      group: 'guess',
      kind: 'question',
      ask: 'guided.guess.date.ask',
      help: 'guided.guess.why',
      next: { best: 'guess', else: 'guess.confirm' },
      escape: 'menu.top',
      negative: 'no',
      options: [
        {
          id: 'yes',
          label: 'guided.common.yes',
          patch: [],
          score: {
            'event-registration': 4200,
            rsvp: 4200,
            'absence-notice': 4200,
            'general-meeting-registration': 4200,
            'conference-registration': 4200,
            'meeting-proxy': 3500,
            'course-signup': 2800,
            'booking-request': 2100,
            'facility-booking': 2100,
            'motion-submission': 2100,
          },
        },
        {
          id: 'no',
          label: 'guided.common.no',
          patch: [],
          score: {
            'contact-enquiry': 2800,
            'customer-feedback': 2800,
            'satisfaction-survey': 2800,
            'quote-request': 2800,
            'support-request': 2800,
            'job-application': 2800,
            'volunteer-signup': 2800,
            'member-details': 2800,
            'newsletter-signup': 2800,
            'suggestion-box': 2800,
            'power-of-attorney': 2800,
            'consent-form': 2800,
          },
        },
        { id: 'unsure', label: 'guided.common.unsure', patch: [] },
      ],
    },
    {
      id: 'guess.meeting',
      group: 'guess',
      kind: 'question',
      ask: 'guided.guess.meeting.ask',
      help: 'guided.guess.why',
      next: { best: 'guess', else: 'guess.confirm' },
      escape: 'menu.top',
      negative: 'no',
      options: [
        {
          id: 'yes',
          label: 'guided.common.yes',
          patch: [],
          score: {
            'motion-submission': 4200,
            'meeting-proxy': 4200,
            'general-meeting-registration': 4200,
            'power-of-attorney': 2100,
          },
        },
        {
          id: 'no',
          label: 'guided.common.no',
          patch: [],
          score: {
            'event-registration': 3500,
            rsvp: 3500,
            'contact-enquiry': 3500,
            'customer-feedback': 3500,
            'satisfaction-survey': 3500,
            'course-signup': 3500,
            'booking-request': 3500,
            'quote-request': 3500,
            'support-request': 3500,
            'job-application': 3500,
            'volunteer-signup': 3500,
            'member-details': 3500,
            'newsletter-signup': 3500,
            'suggestion-box': 3500,
            'facility-booking': 3500,
            'absence-notice': 3500,
            'conference-registration': 3500,
            'lab-observation': 3500,
            'sample-submission': 3500,
            'consent-form': 3500,
            'incident-report': 3500,
          },
        },
        { id: 'unsure', label: 'guided.common.unsure', patch: [] },
      ],
    },
    {
      id: 'guess.reply',
      group: 'guess',
      kind: 'question',
      ask: 'guided.guess.reply.ask',
      help: 'guided.guess.why',
      next: { best: 'guess', else: 'guess.confirm' },
      escape: 'menu.top',
      negative: 'no',
      options: [
        {
          id: 'yes',
          label: 'guided.common.yes',
          patch: [],
          score: {
            'contact-enquiry': 4200,
            'quote-request': 4200,
            'support-request': 4200,
            'booking-request': 3500,
            'job-application': 3500,
            'facility-booking': 2800,
          },
        },
        {
          id: 'no',
          label: 'guided.common.no',
          patch: [],
          score: {
            'event-registration': 2800,
            rsvp: 2800,
            'satisfaction-survey': 2800,
            'course-signup': 2800,
            'member-details': 2800,
            'newsletter-signup': 2800,
            'suggestion-box': 2800,
            'absence-notice': 2800,
            'motion-submission': 2800,
            'meeting-proxy': 2800,
            'general-meeting-registration': 2800,
            'power-of-attorney': 2800,
            'conference-registration': 2800,
            'lab-observation': 2800,
            'sample-submission': 2800,
            'consent-form': 2800,
            'incident-report': 2800,
          },
        },
        { id: 'unsure', label: 'guided.common.unsure', patch: [] },
      ],
    },
    {
      id: 'guess.anonymous',
      group: 'guess',
      kind: 'question',
      ask: 'guided.guess.anonymous.ask',
      help: 'guided.guess.why',
      next: { best: 'guess', else: 'guess.confirm' },
      escape: 'menu.top',
      negative: 'no',
      options: [
        {
          id: 'yes',
          label: 'guided.common.yes',
          patch: [],
          score: {
            'satisfaction-survey': 4200,
            'suggestion-box': 4200,
            'customer-feedback': 2800,
          },
        },
        {
          id: 'no',
          label: 'guided.common.no',
          patch: [],
          score: {
            'event-registration': 3500,
            rsvp: 3500,
            'contact-enquiry': 3500,
            'course-signup': 3500,
            'booking-request': 3500,
            'quote-request': 3500,
            'support-request': 3500,
            'job-application': 3500,
            'volunteer-signup': 3500,
            'member-details': 3500,
            'newsletter-signup': 3500,
            'facility-booking': 3500,
            'absence-notice': 3500,
            'motion-submission': 3500,
            'meeting-proxy': 3500,
            'general-meeting-registration': 3500,
            'power-of-attorney': 3500,
            'conference-registration': 3500,
            'sample-submission': 3500,
            'consent-form': 3500,
          },
        },
        { id: 'unsure', label: 'guided.common.unsure', patch: [] },
      ],
    },
    {
      id: 'guess.signature',
      group: 'guess',
      kind: 'question',
      ask: 'guided.guess.signature.ask',
      help: 'guided.guess.why',
      next: { best: 'guess', else: 'guess.confirm' },
      escape: 'menu.top',
      negative: 'no',
      options: [
        {
          id: 'yes',
          label: 'guided.common.yes',
          patch: [],
          score: {
            'meeting-proxy': 4200,
            'power-of-attorney': 4200,
            'consent-form': 4200,
          },
        },
        {
          id: 'no',
          label: 'guided.common.no',
          patch: [],
          score: {
            'event-registration': 3500,
            rsvp: 3500,
            'contact-enquiry': 3500,
            'customer-feedback': 3500,
            'satisfaction-survey': 3500,
            'course-signup': 3500,
            'booking-request': 3500,
            'quote-request': 3500,
            'support-request': 3500,
            'volunteer-signup': 3500,
            'member-details': 3500,
            'newsletter-signup': 3500,
            'suggestion-box': 3500,
            'facility-booking': 3500,
            'absence-notice': 3500,
            'motion-submission': 3500,
            'general-meeting-registration': 3500,
            'conference-registration': 3500,
            'lab-observation': 3500,
            'sample-submission': 3500,
            'incident-report': 3500,
          },
        },
        { id: 'unsure', label: 'guided.common.unsure', patch: [] },
      ],
    },
    {
      id: 'guess.pay',
      group: 'guess',
      kind: 'question',
      ask: 'guided.guess.pay.ask',
      help: 'guided.guess.why',
      next: { best: 'guess', else: 'guess.confirm' },
      escape: 'menu.top',
      negative: 'no',
      options: [
        {
          id: 'yes',
          label: 'guided.common.yes',
          patch: [],
          score: {
            'course-signup': 4200,
            'conference-registration': 4200,
            'booking-request': 2100,
            'facility-booking': 2100,
          },
        },
        {
          id: 'no',
          label: 'guided.common.no',
          patch: [],
          score: {
            rsvp: 2800,
            'contact-enquiry': 2800,
            'customer-feedback': 2800,
            'satisfaction-survey': 2800,
            'support-request': 2800,
            'job-application': 2800,
            'volunteer-signup': 2800,
            'newsletter-signup': 2800,
            'suggestion-box': 2800,
            'absence-notice': 2800,
            'motion-submission': 2800,
            'meeting-proxy': 2800,
            'general-meeting-registration': 2800,
            'power-of-attorney': 2800,
            'lab-observation': 2800,
            'sample-submission': 2800,
            'consent-form': 2800,
            'incident-report': 2800,
          },
        },
        { id: 'unsure', label: 'guided.common.unsure', patch: [] },
      ],
    },
    {
      id: 'guess.invite',
      group: 'guess',
      kind: 'question',
      ask: 'guided.guess.invite.ask',
      help: 'guided.guess.why',
      next: { best: 'guess', else: 'guess.confirm' },
      escape: 'menu.top',
      negative: 'no',
      options: [
        {
          id: 'yes',
          label: 'guided.common.yes',
          patch: [],
          score: {
            rsvp: 4200,
            'general-meeting-registration': 2800,
            'meeting-proxy': 2100,
          },
        },
        {
          id: 'no',
          label: 'guided.common.no',
          patch: [],
          score: {
            'event-registration': 2800,
            'contact-enquiry': 2800,
            'customer-feedback': 2800,
            'satisfaction-survey': 2800,
            'course-signup': 2800,
            'booking-request': 2800,
            'quote-request': 2800,
            'support-request': 2800,
            'job-application': 2800,
            'volunteer-signup': 2800,
            'member-details': 2800,
            'newsletter-signup': 2800,
            'suggestion-box': 2800,
            'facility-booking': 2800,
            'absence-notice': 2800,
            'conference-registration': 2800,
            'lab-observation': 2800,
            'sample-submission': 2800,
            'consent-form': 2800,
            'incident-report': 2800,
          },
        },
        { id: 'unsure', label: 'guided.common.unsure', patch: [] },
      ],
    },
    {
      id: 'guess.research',
      group: 'guess',
      kind: 'question',
      ask: 'guided.guess.research.ask',
      help: 'guided.guess.why',
      next: { best: 'guess', else: 'guess.confirm' },
      escape: 'menu.top',
      negative: 'no',
      options: [
        {
          id: 'yes',
          label: 'guided.common.yes',
          patch: [],
          score: {
            'lab-observation': 4200,
            'sample-submission': 4200,
          },
        },
        {
          id: 'no',
          label: 'guided.common.no',
          patch: [],
          score: {
            'event-registration': 3500,
            rsvp: 3500,
            'contact-enquiry': 3500,
            'customer-feedback': 3500,
            'satisfaction-survey': 3500,
            'course-signup': 3500,
            'booking-request': 3500,
            'quote-request': 3500,
            'support-request': 3500,
            'job-application': 3500,
            'volunteer-signup': 3500,
            'member-details': 3500,
            'newsletter-signup': 3500,
            'suggestion-box': 3500,
            'facility-booking': 3500,
            'absence-notice': 3500,
            'motion-submission': 3500,
            'meeting-proxy': 3500,
            'general-meeting-registration': 3500,
            'power-of-attorney': 3500,
            'conference-registration': 3500,
            'consent-form': 3500,
            'incident-report': 3500,
          },
        },
        { id: 'unsure', label: 'guided.common.unsure', patch: [] },
      ],
    },
    {
      id: 'guess.samples',
      group: 'guess',
      kind: 'question',
      ask: 'guided.guess.samples.ask',
      help: 'guided.guess.why',
      next: { best: 'guess', else: 'guess.confirm' },
      escape: 'menu.top',
      negative: 'no',
      options: [
        {
          id: 'yes',
          label: 'guided.common.yes',
          patch: [],
          score: {
            'sample-submission': 4200,
          },
        },
        {
          id: 'no',
          label: 'guided.common.no',
          patch: [],
          score: {
            'event-registration': 3500,
            rsvp: 3500,
            'contact-enquiry': 3500,
            'customer-feedback': 3500,
            'satisfaction-survey': 3500,
            'course-signup': 3500,
            'booking-request': 3500,
            'quote-request': 3500,
            'support-request': 3500,
            'job-application': 3500,
            'volunteer-signup': 3500,
            'member-details': 3500,
            'newsletter-signup': 3500,
            'suggestion-box': 3500,
            'facility-booking': 3500,
            'absence-notice': 3500,
            'motion-submission': 3500,
            'meeting-proxy': 3500,
            'general-meeting-registration': 3500,
            'power-of-attorney': 3500,
            'conference-registration': 3500,
            'lab-observation': 3500,
            'consent-form': 3500,
            'incident-report': 3500,
          },
        },
        { id: 'unsure', label: 'guided.common.unsure', patch: [] },
      ],
    },
    {
      id: 'guess.contact',
      group: 'guess',
      kind: 'question',
      ask: 'guided.guess.contact.ask',
      help: 'guided.guess.why',
      next: { best: 'guess', else: 'guess.confirm' },
      escape: 'menu.top',
      negative: 'no',
      options: [
        {
          id: 'yes',
          label: 'guided.common.yes',
          patch: [],
          score: {
            'contact-enquiry': 4200,
            'support-request': 1400,
          },
        },
        {
          id: 'no',
          label: 'guided.common.no',
          patch: [],
          score: {
            'event-registration': 3500,
            rsvp: 3500,
            'customer-feedback': 3500,
            'satisfaction-survey': 3500,
            'course-signup': 3500,
            'booking-request': 3500,
            'quote-request': 3500,
            'job-application': 3500,
            'volunteer-signup': 3500,
            'member-details': 3500,
            'newsletter-signup': 3500,
            'suggestion-box': 3500,
            'facility-booking': 3500,
            'absence-notice': 3500,
            'motion-submission': 3500,
            'meeting-proxy': 3500,
            'general-meeting-registration': 3500,
            'power-of-attorney': 3500,
            'conference-registration': 3500,
            'lab-observation': 3500,
            'sample-submission': 3500,
            'consent-form': 3500,
            'incident-report': 3500,
          },
        },
        { id: 'unsure', label: 'guided.common.unsure', patch: [] },
      ],
    },
    {
      id: 'guess.job',
      group: 'guess',
      kind: 'question',
      ask: 'guided.guess.job.ask',
      help: 'guided.guess.why',
      next: { best: 'guess', else: 'guess.confirm' },
      escape: 'menu.top',
      negative: 'no',
      options: [
        {
          id: 'yes',
          label: 'guided.common.yes',
          patch: [],
          score: {
            'job-application': 4200,
            'volunteer-signup': 4200,
          },
        },
        {
          id: 'no',
          label: 'guided.common.no',
          patch: [],
          score: {
            'event-registration': 3500,
            rsvp: 3500,
            'contact-enquiry': 3500,
            'customer-feedback': 3500,
            'satisfaction-survey': 3500,
            'course-signup': 3500,
            'booking-request': 3500,
            'quote-request': 3500,
            'support-request': 3500,
            'member-details': 3500,
            'newsletter-signup': 3500,
            'suggestion-box': 3500,
            'facility-booking': 3500,
            'absence-notice': 3500,
            'motion-submission': 3500,
            'meeting-proxy': 3500,
            'general-meeting-registration': 3500,
            'power-of-attorney': 3500,
            'conference-registration': 3500,
            'lab-observation': 3500,
            'sample-submission': 3500,
            'consent-form': 3500,
            'incident-report': 3500,
          },
        },
        { id: 'unsure', label: 'guided.common.unsure', patch: [] },
      ],
    },
    {
      id: 'guess.membership',
      group: 'guess',
      kind: 'question',
      ask: 'guided.guess.membership.ask',
      help: 'guided.guess.why',
      next: { best: 'guess', else: 'guess.confirm' },
      escape: 'menu.top',
      negative: 'no',
      options: [
        {
          id: 'yes',
          label: 'guided.common.yes',
          patch: [],
          score: {
            'member-details': 4200,
          },
        },
        {
          id: 'no',
          label: 'guided.common.no',
          patch: [],
          score: {
            'event-registration': 3500,
            rsvp: 3500,
            'contact-enquiry': 3500,
            'customer-feedback': 3500,
            'satisfaction-survey': 3500,
            'course-signup': 3500,
            'booking-request': 3500,
            'quote-request': 3500,
            'support-request': 3500,
            'job-application': 3500,
            'suggestion-box': 3500,
            'facility-booking': 3500,
            'absence-notice': 3500,
            'motion-submission': 3500,
            'meeting-proxy': 3500,
            'general-meeting-registration': 3500,
            'power-of-attorney': 3500,
            'conference-registration': 3500,
            'lab-observation': 3500,
            'sample-submission': 3500,
            'consent-form': 3500,
            'incident-report': 3500,
          },
        },
        { id: 'unsure', label: 'guided.common.unsure', patch: [] },
      ],
    },
    {
      id: 'guess.price',
      group: 'guess',
      kind: 'question',
      ask: 'guided.guess.price.ask',
      help: 'guided.guess.why',
      next: { best: 'guess', else: 'guess.confirm' },
      escape: 'menu.top',
      negative: 'no',
      options: [
        {
          id: 'yes',
          label: 'guided.common.yes',
          patch: [],
          score: {
            'quote-request': 4200,
          },
        },
        {
          id: 'no',
          label: 'guided.common.no',
          patch: [],
          score: {
            'event-registration': 3500,
            rsvp: 3500,
            'contact-enquiry': 3500,
            'customer-feedback': 3500,
            'satisfaction-survey': 3500,
            'course-signup': 3500,
            'support-request': 3500,
            'job-application': 3500,
            'volunteer-signup': 3500,
            'member-details': 3500,
            'newsletter-signup': 3500,
            'suggestion-box': 3500,
            'absence-notice': 3500,
            'motion-submission': 3500,
            'meeting-proxy': 3500,
            'general-meeting-registration': 3500,
            'power-of-attorney': 3500,
            'conference-registration': 3500,
            'lab-observation': 3500,
            'sample-submission': 3500,
            'consent-form': 3500,
            'incident-report': 3500,
          },
        },
        { id: 'unsure', label: 'guided.common.unsure', patch: [] },
      ],
    },
    {
      id: 'guess.problem',
      group: 'guess',
      kind: 'question',
      ask: 'guided.guess.problem.ask',
      help: 'guided.guess.why',
      next: { best: 'guess', else: 'guess.confirm' },
      escape: 'menu.top',
      negative: 'no',
      options: [
        {
          id: 'yes',
          label: 'guided.common.yes',
          patch: [],
          score: {
            'support-request': 4200,
            'incident-report': 4200,
            'customer-feedback': 1400,
          },
        },
        {
          id: 'no',
          label: 'guided.common.no',
          patch: [],
          score: {
            'event-registration': 3500,
            rsvp: 3500,
            'contact-enquiry': 3500,
            'satisfaction-survey': 3500,
            'course-signup': 3500,
            'booking-request': 3500,
            'quote-request': 3500,
            'job-application': 3500,
            'volunteer-signup': 3500,
            'member-details': 3500,
            'newsletter-signup': 3500,
            'facility-booking': 3500,
            'absence-notice': 3500,
            'motion-submission': 3500,
            'meeting-proxy': 3500,
            'general-meeting-registration': 3500,
            'power-of-attorney': 3500,
            'conference-registration': 3500,
            'lab-observation': 3500,
            'sample-submission': 3500,
            'consent-form': 3500,
          },
        },
        { id: 'unsure', label: 'guided.common.unsure', patch: [] },
      ],
    },
    {
      id: 'guess.booking',
      group: 'guess',
      kind: 'question',
      ask: 'guided.guess.booking.ask',
      help: 'guided.guess.why',
      next: { best: 'guess', else: 'guess.confirm' },
      escape: 'menu.top',
      negative: 'no',
      options: [
        {
          id: 'yes',
          label: 'guided.common.yes',
          patch: [],
          score: {
            'booking-request': 4200,
            'facility-booking': 4200,
          },
        },
        {
          id: 'no',
          label: 'guided.common.no',
          patch: [],
          score: {
            'event-registration': 3500,
            rsvp: 3500,
            'contact-enquiry': 3500,
            'customer-feedback': 3500,
            'satisfaction-survey': 3500,
            'quote-request': 3500,
            'support-request': 3500,
            'job-application': 3500,
            'volunteer-signup': 3500,
            'member-details': 3500,
            'newsletter-signup': 3500,
            'suggestion-box': 3500,
            'absence-notice': 3500,
            'motion-submission': 3500,
            'meeting-proxy': 3500,
            'general-meeting-registration': 3500,
            'power-of-attorney': 3500,
            'conference-registration': 3500,
            'lab-observation': 3500,
            'sample-submission': 3500,
            'consent-form': 3500,
            'incident-report': 3500,
          },
        },
        { id: 'unsure', label: 'guided.common.unsure', patch: [] },
      ],
    },
    {
      id: 'guess.place',
      group: 'guess',
      kind: 'question',
      ask: 'guided.guess.place.ask',
      help: 'guided.guess.why',
      next: { best: 'guess', else: 'guess.confirm' },
      escape: 'menu.top',
      negative: 'no',
      options: [
        {
          id: 'yes',
          label: 'guided.common.yes',
          patch: [],
          score: {
            'facility-booking': 4200,
          },
        },
        {
          id: 'no',
          label: 'guided.common.no',
          patch: [],
          score: {
            'event-registration': 3500,
            rsvp: 3500,
            'contact-enquiry': 3500,
            'customer-feedback': 3500,
            'satisfaction-survey': 3500,
            'course-signup': 3500,
            'booking-request': 3500,
            'quote-request': 3500,
            'support-request': 3500,
            'job-application': 3500,
            'volunteer-signup': 3500,
            'member-details': 3500,
            'newsletter-signup': 3500,
            'suggestion-box': 3500,
            'absence-notice': 3500,
            'motion-submission': 3500,
            'meeting-proxy': 3500,
            'general-meeting-registration': 3500,
            'power-of-attorney': 3500,
            'conference-registration': 3500,
            'lab-observation': 3500,
            'sample-submission': 3500,
            'consent-form': 3500,
            'incident-report': 3500,
          },
        },
        { id: 'unsure', label: 'guided.common.unsure', patch: [] },
      ],
    },
    {
      id: 'guess.learn',
      group: 'guess',
      kind: 'question',
      ask: 'guided.guess.learn.ask',
      help: 'guided.guess.why',
      next: { best: 'guess', else: 'guess.confirm' },
      escape: 'menu.top',
      negative: 'no',
      options: [
        {
          id: 'yes',
          label: 'guided.common.yes',
          patch: [],
          score: {
            'course-signup': 4200,
            'conference-registration': 2800,
          },
        },
        {
          id: 'no',
          label: 'guided.common.no',
          patch: [],
          score: {
            'event-registration': 3500,
            rsvp: 3500,
            'contact-enquiry': 3500,
            'customer-feedback': 3500,
            'satisfaction-survey': 3500,
            'booking-request': 3500,
            'quote-request': 3500,
            'support-request': 3500,
            'job-application': 3500,
            'volunteer-signup': 3500,
            'member-details': 3500,
            'newsletter-signup': 3500,
            'suggestion-box': 3500,
            'facility-booking': 3500,
            'absence-notice': 3500,
            'motion-submission': 3500,
            'meeting-proxy': 3500,
            'general-meeting-registration': 3500,
            'power-of-attorney': 3500,
            'lab-observation': 3500,
            'sample-submission': 3500,
            'consent-form': 3500,
            'incident-report': 3500,
          },
        },
        { id: 'unsure', label: 'guided.common.unsure', patch: [] },
      ],
    },
    {
      id: 'guess.sessions',
      group: 'guess',
      kind: 'question',
      ask: 'guided.guess.sessions.ask',
      help: 'guided.guess.why',
      next: { best: 'guess', else: 'guess.confirm' },
      escape: 'menu.top',
      negative: 'no',
      options: [
        {
          id: 'yes',
          label: 'guided.common.yes',
          patch: [],
          score: {
            'course-signup': 4200,
          },
        },
        {
          id: 'no',
          label: 'guided.common.no',
          patch: [],
          score: {
            'event-registration': 3500,
            rsvp: 3500,
            'contact-enquiry': 3500,
            'customer-feedback': 3500,
            'satisfaction-survey': 3500,
            'booking-request': 3500,
            'quote-request': 3500,
            'support-request': 3500,
            'job-application': 3500,
            'newsletter-signup': 3500,
            'suggestion-box': 3500,
            'facility-booking': 3500,
            'absence-notice': 3500,
            'motion-submission': 3500,
            'meeting-proxy': 3500,
            'general-meeting-registration': 3500,
            'power-of-attorney': 3500,
            'conference-registration': 3500,
            'lab-observation': 3500,
            'sample-submission': 3500,
            'consent-form': 3500,
            'incident-report': 3500,
          },
        },
        { id: 'unsure', label: 'guided.common.unsure', patch: [] },
      ],
    },
    {
      id: 'guess.news',
      group: 'guess',
      kind: 'question',
      ask: 'guided.guess.news.ask',
      help: 'guided.guess.why',
      next: { best: 'guess', else: 'guess.confirm' },
      escape: 'menu.top',
      negative: 'no',
      options: [
        {
          id: 'yes',
          label: 'guided.common.yes',
          patch: [],
          score: {
            'newsletter-signup': 4200,
            'member-details': 2100,
          },
        },
        {
          id: 'no',
          label: 'guided.common.no',
          patch: [],
          score: {
            rsvp: 2800,
            'contact-enquiry': 2800,
            'booking-request': 2800,
            'quote-request': 2800,
            'support-request': 2800,
            'job-application': 2800,
            'suggestion-box': 2800,
            'facility-booking': 2800,
            'absence-notice': 2800,
            'motion-submission': 2800,
            'meeting-proxy': 2800,
            'general-meeting-registration': 2800,
            'power-of-attorney': 2800,
            'lab-observation': 2800,
            'sample-submission': 2800,
            'consent-form': 2800,
            'incident-report': 2800,
          },
        },
        { id: 'unsure', label: 'guided.common.unsure', patch: [] },
      ],
    },
    {
      id: 'guess.absence',
      group: 'guess',
      kind: 'question',
      ask: 'guided.guess.absence.ask',
      help: 'guided.guess.why',
      next: { best: 'guess', else: 'guess.confirm' },
      escape: 'menu.top',
      negative: 'no',
      options: [
        {
          id: 'yes',
          label: 'guided.common.yes',
          patch: [],
          score: {
            'absence-notice': 4200,
          },
        },
        {
          id: 'no',
          label: 'guided.common.no',
          patch: [],
          score: {
            'event-registration': 3500,
            'contact-enquiry': 3500,
            'customer-feedback': 3500,
            'satisfaction-survey': 3500,
            'course-signup': 3500,
            'booking-request': 3500,
            'quote-request': 3500,
            'support-request': 3500,
            'job-application': 3500,
            'volunteer-signup': 3500,
            'member-details': 3500,
            'newsletter-signup': 3500,
            'suggestion-box': 3500,
            'facility-booking': 3500,
            'motion-submission': 3500,
            'meeting-proxy': 3500,
            'general-meeting-registration': 3500,
            'power-of-attorney': 3500,
            'conference-registration': 3500,
            'lab-observation': 3500,
            'sample-submission': 3500,
            'consent-form': 3500,
            'incident-report': 3500,
          },
        },
        { id: 'unsure', label: 'guided.common.unsure', patch: [] },
      ],
    },
    {
      id: 'guess.proposal',
      group: 'guess',
      kind: 'question',
      ask: 'guided.guess.proposal.ask',
      help: 'guided.guess.why',
      next: { best: 'guess', else: 'guess.confirm' },
      escape: 'menu.top',
      negative: 'no',
      options: [
        {
          id: 'yes',
          label: 'guided.common.yes',
          patch: [],
          score: {
            'motion-submission': 4200,
            'suggestion-box': 2800,
          },
        },
        {
          id: 'no',
          label: 'guided.common.no',
          patch: [],
          score: {
            'event-registration': 3500,
            rsvp: 3500,
            'contact-enquiry': 3500,
            'customer-feedback': 3500,
            'satisfaction-survey': 3500,
            'course-signup': 3500,
            'booking-request': 3500,
            'quote-request': 3500,
            'support-request': 3500,
            'job-application': 3500,
            'volunteer-signup': 3500,
            'member-details': 3500,
            'newsletter-signup': 3500,
            'facility-booking': 3500,
            'absence-notice': 3500,
            'meeting-proxy': 3500,
            'general-meeting-registration': 3500,
            'conference-registration': 3500,
            'lab-observation': 3500,
            'sample-submission': 3500,
            'consent-form': 3500,
            'incident-report': 3500,
          },
        },
        { id: 'unsure', label: 'guided.common.unsure', patch: [] },
      ],
    },
    {
      id: 'guess.behalf',
      group: 'guess',
      kind: 'question',
      ask: 'guided.guess.behalf.ask',
      help: 'guided.guess.why',
      next: { best: 'guess', else: 'guess.confirm' },
      escape: 'menu.top',
      negative: 'no',
      options: [
        {
          id: 'yes',
          label: 'guided.common.yes',
          patch: [],
          score: {
            'meeting-proxy': 4200,
            'power-of-attorney': 4200,
          },
        },
        {
          id: 'no',
          label: 'guided.common.no',
          patch: [],
          score: {
            'event-registration': 3500,
            rsvp: 3500,
            'contact-enquiry': 3500,
            'customer-feedback': 3500,
            'satisfaction-survey': 3500,
            'course-signup': 3500,
            'booking-request': 3500,
            'quote-request': 3500,
            'support-request': 3500,
            'job-application': 3500,
            'volunteer-signup': 3500,
            'member-details': 3500,
            'newsletter-signup': 3500,
            'suggestion-box': 3500,
            'facility-booking': 3500,
            'absence-notice': 3500,
            'motion-submission': 3500,
            'general-meeting-registration': 3500,
            'conference-registration': 3500,
            'lab-observation': 3500,
            'sample-submission': 3500,
            'consent-form': 3500,
            'incident-report': 3500,
          },
        },
        { id: 'unsure', label: 'guided.common.unsure', patch: [] },
      ],
    },
    // The form's name: its heading on the page, and the masthead's in the brand's preview (S13).
    // Reached once on the guided path; a form read from a document goes on to the brand as before.
    {
      id: 'flow.title',
      group: 'flow',
      kind: 'text-entry',
      ask: 'guided.flow.title.ask',
      help: 'guided.flow.title.help',
      examples: [
        'guided.flow.title.exampleParty',
        'guided.flow.title.exampleCourse',
        'guided.flow.title.exampleMeeting',
      ],
      required: true,
      patch: [{ op: 'set', path: 'draft.title', value: { $answer: true } }],
      next: 'brand.start',
      escape: 'menu.top',
    },
    {
      id: 'brand.start',
      group: 'brand',
      kind: 'question',
      ask: 'guided.brand.start.ask',
      help: 'guided.brand.start.help',
      when: '!has(sidecar.brandDecided)',
      skip: 'guided.skip.brandDecided',
      next: [
        { when: 'pending.brandKitExists == true', to: 'brand.logoSlot' },
        { when: 'true', to: 'brand.quick' },
      ],
      escape: 'menu.siblings(brand)',
      negative: 'later',
      options: [
        {
          id: 'yes',
          label: 'guided.brand.start.yes',
          patch: [{ op: 'set', path: 'sidecar.brandDecided', value: 'organisation' }],
        },
        {
          id: 'later',
          label: 'guided.brand.start.later',
          patch: [{ op: 'set', path: 'sidecar.brandDecided', value: 'default' }],
          // A seeded or imported form has its questions: only "Add another question?" is left.
          next: [
            { when: "has(pending.seeded) || sidecar.provenance != 'guided'", to: 'flow.more' },
            { when: 'true', to: 'text.label' },
          ],
        },
      ],
    },
    {
      id: 'brand.quick',
      group: 'brand',
      kind: 'pick-one',
      ask: 'guided.brand.quick.ask',
      help: 'guided.brand.quick.help',
      // The colours are the organisation's, and only an administrator may change them (owner
      // question 8). The screen asks an administrator before a preset changes the brand kit.
      when: 'pending.canChangeBrand == true',
      skip: 'guided.skip.brandByAdministrator',
      next: 'brand.logoSlot',
      escape: 'menu.siblings(brand)',
      // Loppa's own `default` look is not offered: a user's preview is never in Loppa's colours
      // (docs/plan/CAVEATS.md #32).
      options: [
        {
          id: 'minimal',
          label: 'guided.brand.quick.minimal',
          patch: [{ op: 'set', path: 'pending.themePreset', value: 'minimal' }],
        },
        {
          id: 'garden',
          label: 'guided.brand.quick.garden',
          patch: [{ op: 'set', path: 'pending.themePreset', value: 'garden' }],
        },
        {
          id: 'bold',
          label: 'guided.brand.quick.bold',
          patch: [{ op: 'set', path: 'pending.themePreset', value: 'bold' }],
        },
        {
          id: 'midnight',
          label: 'guided.brand.quick.midnight',
          patch: [{ op: 'set', path: 'pending.themePreset', value: 'midnight' }],
        },
      ],
    },
    {
      id: 'brand.logoSlot',
      group: 'brand',
      kind: 'pick-one',
      ask: 'guided.brand.logoSlot.ask',
      help: 'guided.brand.logoSlot.help',
      next: 'brand.preview',
      escape: 'menu.siblings(brand)',
      preview: 'brand.masthead',
      options: [
        {
          id: 'header-left',
          label: 'guided.brand.logoSlot.headerLeft',
          patch: [
            { op: 'set', path: 'draft.definition.settings.layout.logoSlot', value: 'header-left' },
          ],
        },
        {
          id: 'masthead-centred',
          label: 'guided.brand.logoSlot.mastheadCentred',
          patch: [
            {
              op: 'set',
              path: 'draft.definition.settings.layout.logoSlot',
              value: 'masthead-centred',
            },
          ],
        },
        {
          id: 'corner-watermark',
          label: 'guided.brand.logoSlot.cornerWatermark',
          patch: [
            {
              op: 'set',
              path: 'draft.definition.settings.layout.logoSlot',
              value: 'corner-watermark',
            },
          ],
        },
        {
          id: 'footer-strip',
          label: 'guided.brand.logoSlot.footerStrip',
          patch: [
            { op: 'set', path: 'draft.definition.settings.layout.logoSlot', value: 'footer-strip' },
          ],
        },
        {
          id: 'sidebar-rail',
          label: 'guided.brand.logoSlot.sidebarRail',
          patch: [
            { op: 'set', path: 'draft.definition.settings.layout.logoSlot', value: 'sidebar-rail' },
          ],
        },
        {
          id: 'card-top',
          label: 'guided.brand.logoSlot.cardTop',
          patch: [
            { op: 'set', path: 'draft.definition.settings.layout.logoSlot', value: 'card-top' },
          ],
        },
      ],
    },
    {
      id: 'brand.preview',
      group: 'brand',
      kind: 'preview-moment',
      ask: 'guided.preview.ask',
      help: 'guided.brand.preview.help',
      preview: 'brand.masthead',
      next: [
        { when: "has(pending.seeded) || sidecar.provenance != 'guided'", to: 'flow.more' },
        { when: 'true', to: 'text.label' },
      ],
      escape: 'menu.siblings(brand)',
    },
    {
      id: 'text.label',
      group: 'text',
      kind: 'text-entry',
      ask: 'guided.text.label.ask',
      help: 'guided.text.label.help',
      examples: [
        'guided.text.label.exampleName',
        'guided.text.label.exampleEmail',
        'guided.text.label.exampleDay',
      ],
      required: true,
      patch: [
        // A new question starts with no answer about buttons: the last question's must not leak.
        { op: 'set', path: 'pending.buttons', value: { $unset: true } },
        {
          op: 'add',
          path: 'draft.definition.fields',
          value: { $newField: { type: 'short_text' } },
        },
        { op: 'set', path: 'focus', value: { $lastAddedId: true } },
        { op: 'set', path: 'draft.definition.fields[focus].label', value: { $answer: true } },
      ],
      next: 'text.required',
      escape: 'menu.siblings(text)',
    },
    {
      id: 'text.required',
      group: 'text',
      kind: 'question',
      ask: 'guided.text.required.ask',
      help: 'guided.text.required.help',
      // Reachable from its sibling before any question exists (docs/plan/BUILDER-GRAPH.md,
      // "The machine": the walk found it).
      when: 'has(focus) && !decided(required)',
      skip: [
        { when: '!has(focus)', skip: 'guided.skip.noQuestion' },
        { when: 'true', skip: 'guided.skip.decided' },
      ],
      next: 'choice.buttons',
      escape: 'menu.siblings(text)',
      negative: 'no',
      slot: 'required',
      options: [
        {
          id: 'yes',
          label: 'guided.text.required.yes',
          patch: [{ op: 'set', path: 'draft.definition.fields[focus].required', value: true }],
        },
        {
          id: 'no',
          label: 'guided.text.required.no',
          patch: [{ op: 'set', path: 'draft.definition.fields[focus].required', value: false }],
        },
      ],
    },
    {
      id: 'choice.buttons',
      group: 'choice',
      kind: 'question',
      ask: 'guided.choice.buttons.ask',
      help: 'guided.choice.buttons.help',
      when: 'has(focus) && !decided(kind)',
      skip: [
        { when: '!has(focus)', skip: 'guided.skip.noQuestion' },
        { when: 'true', skip: 'guided.skip.decided' },
      ],
      next: 'choice.answers',
      escape: 'menu.siblings(choice)',
      negative: 'no',
      slot: 'kind',
      options: [
        {
          id: 'yes',
          label: 'guided.common.yes',
          icon: 'check',
          // Buttons from this answer on, one answer by default; "One answer or several?" refines
          // it. So every node after this one finds a choice to shape, however it is reached.
          patch: [
            { op: 'set', path: 'pending.buttons', value: true },
            { op: 'set', path: 'draft.definition.fields[focus].type', value: 'single_select' },
            { op: 'set', path: 'draft.definition.fields[focus].appearance', value: 'buttons' },
          ],
        },
        {
          id: 'no',
          label: 'guided.choice.buttons.no',
          patch: [
            { op: 'set', path: 'pending.buttons', value: false },
            { op: 'set', path: 'draft.definition.fields[focus].type', value: 'short_text' },
          ],
          next: 'text.kind',
        },
      ],
    },
    // What is typed, or ticked, as the answer (S13). In the text group, so a sentence at "Do you
    // want buttons?" never answers it ahead of its turn: what it reads there is as it was. Each card
    // says there are no buttons, so a later jump into the choice chain never shapes options the
    // question no longer has.
    {
      id: 'text.kind',
      group: 'text',
      kind: 'question',
      ask: 'guided.text.kind.ask',
      help: 'guided.text.kind.help',
      when: 'has(focus) && !decided(kind)',
      skip: [
        { when: '!has(focus)', skip: 'guided.skip.noQuestion' },
        { when: 'true', skip: 'guided.skip.decided' },
      ],
      next: [
        { when: 'pending.walking == true && has(pending.toWalk)', to: 'import.next' },
        { when: 'pending.walking == true && !has(sidecar.brandDecided)', to: 'brand.start' },
        { when: 'true', to: 'flow.more' },
      ],
      escape: 'menu.siblings(text)',
      options: [
        {
          id: 'line',
          label: 'guided.text.kind.line',
          detail: 'guided.text.kind.lineDetail',
          patch: [
            { op: 'set', path: 'pending.buttons', value: false },
            { op: 'set', path: 'draft.definition.fields[focus].type', value: 'short_text' },
          ],
        },
        {
          id: 'paragraph',
          label: 'guided.text.kind.paragraph',
          detail: 'guided.text.kind.paragraphDetail',
          patch: [
            { op: 'set', path: 'pending.buttons', value: false },
            { op: 'set', path: 'draft.definition.fields[focus].type', value: 'long_text' },
          ],
        },
        {
          // The consent presentation: its words are the question's own, typed by the person
          // (`CLAUDE.md` rule 8, ADR 0012). Required means it must be ticked.
          id: 'tick',
          label: 'guided.text.kind.tick',
          detail: 'guided.text.kind.tickDetail',
          patch: [
            { op: 'set', path: 'pending.buttons', value: false },
            { op: 'set', path: 'draft.definition.fields[focus].type', value: 'yes_no' },
            { op: 'set', path: 'draft.definition.fields[focus].appearance', value: 'checkbox' },
          ],
        },
      ],
    },
    {
      id: 'choice.answers',
      group: 'choice',
      kind: 'question',
      ask: 'guided.choice.answers.ask',
      help: 'guided.choice.answers.help',
      when: 'pending.buttons == true && !decided(kind)',
      skip: [
        { when: 'pending.buttons == false', skip: 'guided.skip.noButtons' },
        // An imported question's kind was the document's (S12).
        { when: 'decided(kind)', skip: 'guided.skip.decided' },
        { when: 'true', skip: 'guided.skip.noButtons' },
      ],
      next: 'choice.count',
      escape: 'menu.siblings(choice)',
      slot: 'kind',
      options: [
        {
          id: 'one',
          label: 'guided.choice.answers.one',
          patch: [
            { op: 'set', path: 'draft.definition.fields[focus].type', value: 'single_select' },
            { op: 'set', path: 'draft.definition.fields[focus].appearance', value: 'buttons' },
          ],
        },
        {
          id: 'many',
          label: 'guided.choice.answers.many',
          patch: [
            { op: 'set', path: 'draft.definition.fields[focus].type', value: 'multi_select' },
            { op: 'set', path: 'draft.definition.fields[focus].appearance', value: 'buttons' },
          ],
        },
      ],
    },
    {
      id: 'choice.count',
      group: 'choice',
      kind: 'quantity',
      ask: 'guided.choice.count.ask',
      help: 'guided.choice.count.help',
      // A question that is a choice already — imported (S12) — is asked too.
      when: '(pending.buttons == true || has(draft.definition.fields[focus].options)) && !decided(options)',
      skip: [
        { when: 'pending.buttons == false', skip: 'guided.skip.noButtons' },
        { when: '!has(draft.definition.fields[focus].options)', skip: 'guided.skip.notAChoice' },
        { when: 'true', skip: 'guided.skip.decided' },
      ],
      min: 2,
      max: 12,
      default: 3,
      slot: 'options',
      patch: [
        {
          op: 'set',
          path: 'draft.definition.fields[focus].options',
          value: { $options: { $answer: true } },
        },
      ],
      next: 'choice.shape',
      escape: 'menu.siblings(choice)',
    },
    {
      id: 'choice.shape',
      group: 'choice',
      kind: 'pick-one',
      ask: 'guided.choice.shape.ask',
      help: 'guided.choice.shape.help',
      // A question that is a choice already — imported (S12) — is asked too.
      when: '(pending.buttons == true || has(draft.definition.fields[focus].options)) && !decided(shape)',
      skip: [
        { when: 'pending.buttons == false', skip: 'guided.skip.noButtons' },
        { when: '!has(draft.definition.fields[focus].options)', skip: 'guided.skip.notAChoice' },
        { when: 'true', skip: 'guided.skip.decided' },
      ],
      next: 'choice.placement',
      escape: 'menu.siblings(choice)',
      preview: 'choice.control',
      slot: 'shape',
      options: [
        {
          id: 'pill',
          label: 'guided.choice.shape.pill',
          patch: [
            { op: 'set', path: 'draft.definition.fields[focus].appearance', value: 'buttons' },
            { op: 'set', path: 'draft.definition.fields[focus].style.shape', value: 'pill' },
          ],
        },
        {
          id: 'rounded',
          label: 'guided.choice.shape.rounded',
          patch: [
            { op: 'set', path: 'draft.definition.fields[focus].appearance', value: 'buttons' },
            { op: 'set', path: 'draft.definition.fields[focus].style.shape', value: 'rounded' },
          ],
        },
        {
          id: 'square',
          label: 'guided.choice.shape.square',
          patch: [
            { op: 'set', path: 'draft.definition.fields[focus].appearance', value: 'buttons' },
            { op: 'set', path: 'draft.definition.fields[focus].style.shape', value: 'square' },
          ],
        },
        // Every shape is a way of drawing buttons, so choosing one makes them buttons: a shape on a
        // dropdown — an imported choice's (S12) — would change nothing anyone could see.
        {
          id: 'tab',
          label: 'guided.choice.shape.tab',
          patch: [
            { op: 'set', path: 'draft.definition.fields[focus].appearance', value: 'buttons' },
            { op: 'set', path: 'draft.definition.fields[focus].style.shape', value: 'tab' },
          ],
        },
        {
          id: 'segmented',
          label: 'guided.choice.shape.segmented',
          patch: [
            { op: 'set', path: 'draft.definition.fields[focus].appearance', value: 'buttons' },
            { op: 'set', path: 'draft.definition.fields[focus].style.shape', value: 'segmented' },
          ],
        },
        {
          id: 'tile',
          label: 'guided.choice.shape.tile',
          // A tile is the `cards` appearance, which already exists — not a new shape.
          patch: [{ op: 'set', path: 'draft.definition.fields[focus].appearance', value: 'cards' }],
        },
      ],
    },
    {
      id: 'choice.placement',
      group: 'choice',
      kind: 'pick-one',
      ask: 'guided.choice.placement.ask',
      help: 'guided.choice.placement.help',
      // A question that is a choice already — imported (S12) — is asked too.
      when: '(pending.buttons == true || has(draft.definition.fields[focus].options)) && !decided(placement)',
      skip: [
        { when: 'pending.buttons == false', skip: 'guided.skip.noButtons' },
        { when: '!has(draft.definition.fields[focus].options)', skip: 'guided.skip.notAChoice' },
        { when: 'true', skip: 'guided.skip.decided' },
      ],
      next: 'choice.preview',
      escape: 'menu.siblings(choice)',
      slot: 'placement',
      options: [
        {
          id: 'under-full',
          label: 'guided.choice.placement.underFull',
          patch: [
            { op: 'set', path: 'draft.definition.fields[focus].width', value: 'full' },
            { op: 'set', path: 'draft.definition.fields[focus].style.columns', value: '1' },
          ],
        },
        {
          id: 'row',
          label: 'guided.choice.placement.row',
          patch: [
            { op: 'set', path: 'draft.definition.fields[focus].style.columns', value: 'auto' },
          ],
        },
      ],
    },
    {
      id: 'choice.preview',
      group: 'choice',
      kind: 'preview-moment',
      ask: 'guided.preview.ask',
      help: 'guided.choice.preview.help',
      preview: 'choice.control',
      // While a walk is going (S12): the next question from the document, and at its end the brand.
      next: [
        { when: 'pending.walking == true && has(pending.toWalk)', to: 'import.next' },
        { when: 'pending.walking == true && !has(sidecar.brandDecided)', to: 'brand.start' },
        { when: 'true', to: 'flow.more' },
      ],
      escape: 'menu.siblings(choice)',
    },
    // The walk over a form read from a document (S12, `docs/plan/CONVERGENCE.md`). Which question is
    // next is the machine's (`pending.toWalk`): the first after the focus, in the form's order, with
    // something still open. Each walked question goes through the chain every question does.
    {
      id: 'import.walk',
      group: 'import',
      kind: 'question',
      ask: 'guided.import.walk.ask',
      help: 'guided.import.walk.help',
      when: 'has(pending.toWalk)',
      skip: 'guided.skip.nothingToWalk',
      next: [
        { when: '!has(sidecar.brandDecided)', to: 'brand.start' },
        { when: 'true', to: 'flow.more' },
      ],
      escape: 'menu.top',
      negative: 'no',
      options: [
        {
          id: 'yes',
          label: 'guided.import.walk.yes',
          patch: [
            // A question starts with no answer about buttons: the last one's must not leak.
            { op: 'set', path: 'pending.buttons', value: { $unset: true } },
            { op: 'set', path: 'focus', value: { $toWalk: true } },
            { op: 'set', path: 'pending.walking', value: true },
          ],
          next: [
            { when: 'has(focus)', to: 'text.required' },
            { when: 'true', to: 'flow.more' },
          ],
        },
        { id: 'no', label: 'guided.import.walk.no', patch: [] },
      ],
    },
    {
      id: 'import.next',
      group: 'import',
      kind: 'question',
      ask: 'guided.import.next.ask',
      help: 'guided.import.next.help',
      when: 'has(pending.toWalk)',
      skip: 'guided.skip.nothingToWalk',
      next: [
        { when: '!has(sidecar.brandDecided)', to: 'brand.start' },
        { when: 'true', to: 'flow.more' },
      ],
      escape: 'menu.top',
      negative: 'no',
      options: [
        {
          id: 'yes',
          label: 'guided.import.next.yes',
          patch: [
            { op: 'set', path: 'pending.buttons', value: { $unset: true } },
            { op: 'set', path: 'focus', value: { $toWalk: true } },
          ],
          next: [
            { when: 'has(focus)', to: 'text.required' },
            { when: 'true', to: 'flow.more' },
          ],
        },
        {
          id: 'no',
          label: 'guided.import.next.no',
          patch: [{ op: 'set', path: 'pending.walking', value: false }],
        },
      ],
    },
    {
      id: 'flow.more',
      group: 'flow',
      kind: 'question',
      ask: 'guided.flow.more.ask',
      help: 'guided.flow.more.help',
      next: 'end',
      escape: 'menu.top',
      negative: 'no',
      options: [
        {
          id: 'yes',
          label: 'guided.flow.more.yes',
          patch: [],
          next: 'text.label',
        },
        { id: 'no', label: 'guided.flow.more.no', patch: [], next: 'end' },
      ],
    },
    {
      id: 'menu.top',
      group: 'menu',
      kind: 'menu',
      ask: 'guided.menu.top.ask',
      help: 'guided.menu.top.help',
      entries: [
        'flow.start',
        'import.walk',
        'brand.start',
        'text.label',
        'choice.buttons',
        'flow.more',
      ],
      next: 'flow.more',
      escape: 'menu.top',
    },
    {
      id: 'end',
      group: 'flow',
      kind: 'end',
      ask: 'guided.end.ask',
      help: 'guided.end.help',
    },
  ],
} as const satisfies BuilderGraph;
