import type { InvoiceStrings } from './invoice.js';

/**
 * The wording on an invoice, in the languages this product publishes in.
 *
 * A tenant reads their invoice in their own language or they ring somebody about it. The same
 * reasoning as the admission card, and the same failure the admission card already had once: it
 * shipped in two of twelve languages and nothing noticed until a test counted them.
 *
 * `INVOICE_LOCALES` is exported so a test can compare this against the product's locale list. Two
 * lists that must agree, with something comparing them.
 */
export const INVOICE_COPY: Record<string, InvoiceStrings> = {
  'sv-SE': {
    invoice: 'Faktura',
    issuedOn: 'Fakturadatum',
    dueOn: 'Förfallodatum',
    period: 'Avser perioden',
    reference: 'OCR-nummer',
    payTo: 'Bankgiro',
    description: 'Specifikation',
    quantity: 'Antal',
    unitPrice: 'À-pris',
    amount: 'Belopp',
    net: 'Netto',
    vat: 'Moms',
    total: 'Summa',
    toPay: 'Att betala',
    settled: 'Betald. Tack.',
  },
  'en-GB': {
    invoice: 'Invoice',
    issuedOn: 'Invoice date',
    dueOn: 'Due date',
    period: 'For the period',
    reference: 'Payment reference',
    payTo: 'Bankgiro',
    description: 'Description',
    quantity: 'Quantity',
    unitPrice: 'Unit price',
    amount: 'Amount',
    net: 'Net',
    vat: 'VAT',
    total: 'Total',
    toPay: 'To pay',
    settled: 'Paid. Thank you.',
  },
  'da-DK': {
    invoice: 'Faktura',
    issuedOn: 'Fakturadato',
    dueOn: 'Forfaldsdato',
    period: 'For perioden',
    reference: 'Betalingsreference',
    payTo: 'Bankkonto',
    description: 'Beskrivelse',
    quantity: 'Antal',
    unitPrice: 'Stykpris',
    amount: 'Beløb',
    net: 'Netto',
    vat: 'Moms',
    total: 'I alt',
    toPay: 'At betale',
    settled: 'Betalt. Tak.',
  },
  'nb-NO': {
    invoice: 'Faktura',
    issuedOn: 'Fakturadato',
    dueOn: 'Forfallsdato',
    period: 'For perioden',
    reference: 'KID-nummer',
    payTo: 'Kontonummer',
    description: 'Beskrivelse',
    quantity: 'Antall',
    unitPrice: 'Enhetspris',
    amount: 'Beløp',
    net: 'Netto',
    vat: 'Mva',
    total: 'Sum',
    toPay: 'Å betale',
    settled: 'Betalt. Takk.',
  },
  'fi-FI': {
    invoice: 'Lasku',
    issuedOn: 'Laskun päivämäärä',
    dueOn: 'Eräpäivä',
    period: 'Ajalta',
    reference: 'Viitenumero',
    payTo: 'Tilinumero',
    description: 'Selite',
    quantity: 'Määrä',
    unitPrice: 'Yksikköhinta',
    amount: 'Summa',
    net: 'Netto',
    vat: 'Alv',
    total: 'Yhteensä',
    toPay: 'Maksettava',
    settled: 'Maksettu. Kiitos.',
  },
  'is-IS': {
    invoice: 'Reikningur',
    issuedOn: 'Dagsetning',
    dueOn: 'Eindagi',
    period: 'Fyrir tímabilið',
    reference: 'Greiðslutilvísun',
    payTo: 'Reikningsnúmer',
    description: 'Lýsing',
    quantity: 'Magn',
    unitPrice: 'Einingaverð',
    amount: 'Upphæð',
    net: 'Nettó',
    vat: 'VSK',
    total: 'Samtals',
    toPay: 'Til greiðslu',
    settled: 'Greitt. Takk.',
  },
  'de-DE': {
    invoice: 'Rechnung',
    issuedOn: 'Rechnungsdatum',
    dueOn: 'Fällig am',
    period: 'Für den Zeitraum',
    reference: 'Verwendungszweck',
    payTo: 'Konto',
    description: 'Beschreibung',
    quantity: 'Menge',
    unitPrice: 'Einzelpreis',
    amount: 'Betrag',
    net: 'Netto',
    vat: 'MwSt.',
    total: 'Gesamt',
    toPay: 'Zu zahlen',
    settled: 'Bezahlt. Danke.',
  },
  'fr-FR': {
    invoice: 'Facture',
    issuedOn: 'Date de facture',
    dueOn: 'Échéance',
    period: 'Pour la période',
    reference: 'Référence de paiement',
    payTo: 'Compte',
    description: 'Description',
    quantity: 'Quantité',
    unitPrice: 'Prix unitaire',
    amount: 'Montant',
    net: 'Net',
    vat: 'TVA',
    total: 'Total',
    toPay: 'À payer',
    settled: 'Payée. Merci.',
  },
  'es-ES': {
    invoice: 'Factura',
    issuedOn: 'Fecha de factura',
    dueOn: 'Vencimiento',
    period: 'Del periodo',
    reference: 'Referencia de pago',
    payTo: 'Cuenta',
    description: 'Descripción',
    quantity: 'Cantidad',
    unitPrice: 'Precio unitario',
    amount: 'Importe',
    net: 'Neto',
    vat: 'IVA',
    total: 'Total',
    toPay: 'A pagar',
    settled: 'Pagada. Gracias.',
  },
  'ru-RU': {
    invoice: 'Счёт',
    issuedOn: 'Дата счёта',
    dueOn: 'Срок оплаты',
    period: 'За период',
    reference: 'Назначение платежа',
    payTo: 'Счёт получателя',
    description: 'Описание',
    quantity: 'Количество',
    unitPrice: 'Цена за единицу',
    amount: 'Сумма',
    net: 'Без налога',
    vat: 'НДС',
    total: 'Итого',
    toPay: 'К оплате',
    settled: 'Оплачено. Спасибо.',
  },
  'ja-JP': {
    invoice: '請求書',
    issuedOn: '請求日',
    dueOn: 'お支払期限',
    period: '対象期間',
    reference: 'お支払い番号',
    payTo: '振込先',
    description: '内訳',
    quantity: '数量',
    unitPrice: '単価',
    amount: '金額',
    net: '小計',
    vat: '消費税',
    total: '合計',
    toPay: 'お支払金額',
    settled: 'お支払い済みです。ありがとうございます。',
  },
  'zh-CN': {
    invoice: '账单',
    issuedOn: '开具日期',
    dueOn: '到期日',
    period: '账期',
    reference: '付款识别号',
    payTo: '收款账户',
    description: '项目',
    quantity: '数量',
    unitPrice: '单价',
    amount: '金额',
    net: '小计',
    vat: '增值税',
    total: '合计',
    toPay: '应付金额',
    settled: '已付款，谢谢。',
  },
};

export const INVOICE_LOCALES = Object.keys(INVOICE_COPY);

/**
 * The wording for a locale, falling back to the organisation's default and then to Swedish.
 *
 * Not `locale.split('-')[0]`. That fallback has been written twice in this codebase and removed
 * twice: it turns `sv-FI` into `sv`, which is not a locale anything here has copy for, and then
 * silently produces nothing.
 */
export function invoiceCopy(locale: string, fallback = 'sv-SE'): InvoiceStrings {
  return INVOICE_COPY[locale] ?? INVOICE_COPY[fallback] ?? INVOICE_COPY['sv-SE']!;
}
