import type { LayoutLanguage } from './lexicon.js';

/**
 * An ordinary paragraph of form instructions in each shipped language, written for these tests:
 * what §2.11 must recognise. Each is the kind of text that sits at the top of a registration form.
 */
export const PROSE: Readonly<Record<LayoutLanguage, string>> = {
  da: 'Hvis du vil deltage i årsmødet, skal du udfylde blanketten og sende den til os senest fredag. Vi har brug for at vide, hvor mange af jer der kommer, hvad I gerne vil spise, og om nogle af jer har allergier. Det er vigtigt at alle oplysninger er korrekte, for ellers kan vi ikke nå at sende indkaldelsen ud i tide. Skriv tydeligt, og kontrollér at du har svaret på alt, før du afleverer den. Hvis noget er uklart, bedes du venligst kontakte sekretariatet, så hjælper vi dig gennem det. Blanketten bliver gemt hos os, og ingen andre end bestyrelsen får adgang til den, uden at du har givet os lov. Mellem mødets punkter blev der tidligere holdt pauser, og det bliver der også i år, så du kan tale med hende eller ham, som står for maden.',
  de: 'Wenn Sie an der Jahresversammlung teilnehmen möchten, füllen Sie bitte das Formular aus und senden Sie es bis Freitag an uns zurück. Wir müssen wissen, wie viele Personen kommen, was Sie essen möchten und ob jemand von Ihnen Allergien hat. Es ist wichtig, dass alle Angaben richtig sind, sonst können wir die Einladung nicht rechtzeitig verschicken. Schreiben Sie bitte deutlich und prüfen Sie, ob Sie alle Fragen beantwortet haben. Wenn etwas unklar ist, wenden Sie sich an das Sekretariat, das Ihnen gerne mit der Anmeldung hilft.',
  en: 'If you would like to take part in the annual meeting, please fill in this form and return it to us by Friday. We need to know how many of you are coming, what you would like to eat and whether any of you have allergies. It is important that all the details are correct, as otherwise we will not be able to send the invitation in time. Please write clearly and check that you have answered every question before you hand it in. If anything is unclear, the office will be happy to help you with your registration.',
  es: 'Si desea participar en la asamblea anual, rellene este formulario y envíenoslo antes del viernes. Necesitamos saber cuántas personas vendrán, qué desean comer y si alguno de ustedes tiene alergias. Es importante que todos los datos sean correctos, porque de lo contrario no podremos enviar la convocatoria a tiempo. Por favor, escriba con claridad y compruebe que ha respondido a todas las preguntas antes de entregarlo. Si algo no está claro, la secretaría le ayudará con mucho gusto con su inscripción, como también con cualquier duda sobre el lugar de la reunión.',
  fi: 'Jos haluat osallistua vuosikokoukseen, täytä tämä lomake ja palauta se meille perjantaihin mennessä. Meidän täytyy tietää, kuinka moni teistä tulee, mitä haluatte syödä ja onko kenelläkään teistä allergioita. On tärkeää, että kaikki tiedot ovat oikein, koska muuten emme voi lähettää kutsua ajoissa. Kirjoita selvästi ja tarkista, että olet vastannut kaikkiin kysymyksiin ennen kuin palautat lomakkeen. Jos jokin on epäselvää, sihteeristö auttaa sinua mielellään ilmoittautumisessa, ja voit myös soittaa meille tai lähettää sähköpostia kokouksen jälkeen.',
  fr: "Si vous souhaitez participer à l'assemblée annuelle, veuillez remplir ce formulaire et nous le renvoyer avant vendredi. Nous devons savoir combien de personnes viendront, ce que vous souhaitez manger et si l'un de vous a des allergies. Il est important que toutes les informations soient exactes, sinon nous ne pourrons pas envoyer la convocation à temps. Veuillez écrire lisiblement et vérifier que vous avez répondu à toutes les questions avant de le rendre. Si quelque chose n'est pas clair, le secrétariat vous aidera volontiers pour votre inscription et pour tous les détails sur le lieu.",
  is: 'Ef þú vilt taka þátt í aðalfundinum skaltu fylla út þetta eyðublað og skila því til okkar fyrir föstudag. Við þurfum að vita hversu mörg ykkar koma, hvað þið viljið borða og hvort einhver ykkar sé með ofnæmi. Það er mikilvægt að allar upplýsingar séu réttar, annars getum við ekki sent fundarboðið í tæka tíð. Vinsamlegast skrifaðu skýrt og athugaðu að þú hafir svarað öllum spurningum áður en þú skilar því. Ef eitthvað er óljóst mun skrifstofan hjálpa þér með skráninguna, og hún verður opin eftir fundinn fyrir þá sem vilja spyrja um það.',
  ja: '年次総会に参加を希望される方は、この用紙に記入し、金曜日までにご提出ください。何名が参加されるか、お食事のご希望、アレルギーの有無をお知らせいただく必要があります。すべての情報が正しいことが大切です。そうでないと、招待状を期日までにお送りすることができません。はっきりとご記入のうえ、すべての質問に答えたことをご確認ください。ご不明な点がありましたら、事務局までお問い合わせください。',
  nb: 'Hvis du vil delta på årsmøtet, må du fylle ut skjemaet og sende det til oss innen fredag. Vi trenger å vite hvor mange av dere som kommer, hva dere ønsker å spise, og om noen av dere har allergier. Det er viktig at alle opplysningene er riktige, ellers rekker vi ikke å sende innkallingen ut i tide. Skriv tydelig, og sjekk at du har svart på alt før du leverer det. Hvis noe er uklart, ta vennligst kontakt med sekretariatet, så hjelper vi deg gjennom det. Skjemaet blir lagret hos oss, og ingen utenom styret får se det uten at du har gitt oss lov. Mellom punktene ble det tidligere holdt pauser, og det blir det også i år, så du kan snakke med meg eller med dem som har ansvar for maten etter møtet.',
  ru: 'Если вы хотите принять участие в ежегодном собрании, пожалуйста, заполните эту форму и отправьте её нам до пятницы. Нам нужно знать, сколько человек придёт, что вы хотите есть и есть ли у кого-то из вас аллергия. Важно, чтобы все данные были верными, иначе мы не сможем вовремя отправить приглашение. Пишите разборчиво и проверьте, что вы ответили на все вопросы, прежде чем сдать форму. Если что-то непонятно, секретариат с радостью поможет вам с регистрацией, и вы можете написать нам или позвонить до собрания.',
  sv: 'Om du vill delta i årsmötet måste du fylla i blanketten och lämna den till oss senast på fredag. Vi behöver veta hur många av er som kommer, vad ni vill äta och om någon av er har allergier. Det är viktigt att alla uppgifter är korrekta, annars hinner vi inte skicka ut kallelsen i tid. Skriv tydligt och kontrollera att du har svarat på allt innan du lämnar in den. Om något är oklart kan du vänligen kontakta kansliet, så hjälper vi dig genom det. Blanketten sparas hos oss och ingen utom styrelsen får se den utan att du har gett oss lov. Mellan punkterna har det tidigare varit pauser, och det blir det också i år, så att du kan prata med dem som har hand om maten.',
  zh: '如果您想参加年度大会，请填写这张表格，并在星期五之前交给我们。我们需要知道有多少人会来，您想吃什么，以及你们中是否有人对食物过敏。所有信息都必须正确，这一点很重要，否则我们将无法及时把邀请寄给您。请写清楚，并在交表之前检查您是否已经回答了所有问题。如果有什么不清楚的地方，请联系秘书处，我们会很乐意为您提供帮助。',
};
